-- Script was generated by Devart dbForge Studio for MySQL, Version 5.0.97.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2/11/2013 8:45:26 PM
-- Server version: 5.5.30
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE hivemind;

--
-- Definition for table character_data
--
DROP TABLE IF EXISTS character_data;
CREATE TABLE character_data (
  CharacterID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PlayerUID VARCHAR(32) NOT NULL,
  InstanceID INT(11) NOT NULL,
  Datestamp DATETIME DEFAULT NULL,
  LastLogin DATETIME NOT NULL,
  Inventory TEXT DEFAULT NULL,
  Backpack TEXT DEFAULT NULL,
  Worldspace VARCHAR(128) NOT NULL DEFAULT '[]',
  Medical VARCHAR(256) NOT NULL DEFAULT '[]',
  Alive TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  Generation INT(11) UNSIGNED NOT NULL DEFAULT 1,
  LastAte DATETIME NOT NULL,
  LastDrank DATETIME NOT NULL,
  KillsZ INT(11) UNSIGNED NOT NULL DEFAULT 0,
  HeadshotsZ INT(11) UNSIGNED NOT NULL DEFAULT 0,
  DistanceFoot INT(11) NOT NULL DEFAULT 0,
  Duration INT(11) UNSIGNED NOT NULL DEFAULT 0,
  CurrentState VARCHAR(128) NOT NULL DEFAULT '[]',
  KillsH INT(11) UNSIGNED NOT NULL DEFAULT 0,
  Model VARCHAR(64) NOT NULL DEFAULT '"Survivor2_DZ"',
  KillsB INT(11) UNSIGNED NOT NULL DEFAULT 0,
  Humanity INT(11) NOT NULL DEFAULT 2500,
  PRIMARY KEY (CharacterID),
  INDEX CharFetch (PlayerUID, Alive)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table dbver
--
DROP TABLE IF EXISTS dbver;
CREATE TABLE dbver (
  version MEDIUMINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (version)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 7
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table object_classes
--
DROP TABLE IF EXISTS object_classes;
CREATE TABLE object_classes (
  Classname VARCHAR(32) NOT NULL DEFAULT '',
  Chance DECIMAL(6, 5) NOT NULL DEFAULT 0.00000,
  MaxNum TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  Damage VARCHAR(20) NOT NULL DEFAULT '0',
  Hitpoints VARCHAR(999) NOT NULL DEFAULT '[]',
  MaxFuel VARCHAR(10) DEFAULT '0',
  Inventory TEXT DEFAULT NULL,
  PRIMARY KEY (Classname)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 101
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table object_data
--
DROP TABLE IF EXISTS object_data;
CREATE TABLE object_data (
  ObjectID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  ObjectUID BIGINT(20) NOT NULL DEFAULT 0,
  Instance INT(11) NOT NULL,
  Classname VARCHAR(64) DEFAULT NULL,
  Datestamp DATETIME NOT NULL,
  CharacterID INT(11) UNSIGNED NOT NULL DEFAULT 0,
  Worldspace VARCHAR(128) NOT NULL DEFAULT '[]',
  Inventory TEXT DEFAULT NULL,
  Hitpoints VARCHAR(512) NOT NULL DEFAULT '[]',
  Fuel DOUBLE(13, 5) NOT NULL DEFAULT 1.00000,
  Damage DOUBLE(13, 5) NOT NULL DEFAULT 0.00000,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  Landmark TINYINT(4) DEFAULT 0,
  PRIMARY KEY (ObjectID),
  INDEX Instance (Instance),
  INDEX ObjectUID (ObjectUID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table object_spawns
--
DROP TABLE IF EXISTS object_spawns;
CREATE TABLE object_spawns (
  ObjectUID VARCHAR(20) NOT NULL DEFAULT '',
  Classname VARCHAR(32) DEFAULT NULL,
  Worldspace VARCHAR(64) DEFAULT NULL,
  Description VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ObjectUID)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 76
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table player_data
--
DROP TABLE IF EXISTS player_data;
CREATE TABLE player_data (
  PlayerUID VARCHAR(32) NOT NULL,
  PlayerName VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PlayerMorality INT(11) NOT NULL DEFAULT 0,
  PlayerSex TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (PlayerUID)
)
ENGINE = MYISAM
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table player_login
--
DROP TABLE IF EXISTS player_login;
CREATE TABLE player_login (
  LoginID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  PlayerUID VARCHAR(32) NOT NULL,
  CharacterID INT(11) UNSIGNED NOT NULL,
  Datestamp DATETIME NOT NULL,
  `Action` TINYINT(3) NOT NULL,
  PRIMARY KEY (LoginID)
)
ENGINE = MYISAM
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

DELIMITER $$

--
-- Definition for procedure pCleanup
--
DROP PROCEDURE IF EXISTS pCleanup$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pCleanup()
BEGIN

  CALL pCleanupOOB();

  DELETE
  FROM
    object_data
  WHERE
    Damage = '1';

  DELETE
  FROM
    object_data
  WHERE
    date(object_data.Datestamp) < curdate() - INTERVAL 9 DAY
    AND CharacterID = 0
    AND (Inventory = '[]'
    OR (Inventory = '[[[],[]],[[],[]],[[],[]]]'
    AND Classname = 'TentStorage'));

  UPDATE object_data, character_data
  SET
    object_data.characterID = 0, object_data.Datestamp = curdate()
  WHERE
    object_data.CharacterID = character_data.CharacterID
    AND character_data.Alive = 0
    AND date(character_data.Datestamp) < curdate() - INTERVAL 3 DAY;

  UPDATE object_data, character_data
  SET
    object_data.characterID = 0, object_data.Datestamp = curdate()
  WHERE
    object_data.CharacterID = character_data.CharacterID
    AND date(character_data.LastLogin) < curdate() - INTERVAL 7 DAY;

END
$$

--
-- Definition for procedure pCleanupOOB
--
DROP PROCEDURE IF EXISTS pCleanupOOB$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pCleanupOOB()
BEGIN

  DECLARE intLineCount  INT DEFAULT 0;
  DECLARE intDummyCount INT DEFAULT 0;
  DECLARE intDoLine     INT DEFAULT 0;
  DECLARE intWest       INT DEFAULT 0;
  DECLARE intNorth      INT DEFAULT 0;

  SELECT count(*)
  INTO
    intLineCount
  FROM
    object_data;

  SELECT count(*)
  INTO
    intDummyCount
  FROM
    object_data
  WHERE
    Classname = 'dummy';

  WHILE (intLineCount > intDummyCount)
  DO

    SET intDoLine = intLineCount - 1;

    SELECT ObjectUID
         , Worldspace
    INTO
      @rsObjectUID, @rsWorldspace
    FROM
      object_data
    LIMIT
      intDoLine, 1;

    SELECT replace(@rsWorldspace, '[', '')
    INTO
      @rsWorldspace;
    SELECT replace(@rsWorldspace, ']', '')
    INTO
      @rsWorldspace;
    SELECT replace(substring(substring_index(@rsWorldspace, ',', 2), length(substring_index(@rsWorldspace, ',', 2 - 1)) + 1), ',', '')
    INTO
      @West;
    SELECT replace(substring(substring_index(@rsWorldspace, ',', 3), length(substring_index(@rsWorldspace, ',', 3 - 1)) + 1), ',', '')
    INTO
      @North;

    SELECT instr(@West, '-')
    INTO
      intWest;
    SELECT instr(@North, '-')
    INTO
      intNorth;

    IF (intNorth = 0) THEN
      IF (@North = NULL) THEN
        SET @North = '';
        SELECT convert(@North, DECIMAL(16, 8))
        INTO
          intNorth;
      END IF;
      IF (@North != NULL) THEN
        SELECT convert(@North, DECIMAL(16, 8))
        INTO
          intNorth;
      END IF;
    END IF;

    IF (intWest > 0 OR intNorth > 15360) THEN
      DELETE
      FROM
        object_data
      WHERE
        ObjectUID = @rsObjectUID;
    END IF;

    SET intLineCount = intLineCount - 1;

  END WHILE;

END
$$

--
-- Definition for procedure pFixMaxNum
--
DROP PROCEDURE IF EXISTS pFixMaxNum$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pFixMaxNum()
BEGIN

  DECLARE iCounter INT DEFAULT 0;

  SELECT count(*)
  INTO
    @iClassesCount
  FROM
    object_classes
  WHERE
    Classname <> '';
  WHILE (iCounter < @iClassesCount)
  DO
    SELECT Classname
         , MaxNum
    INTO
      @Classname, @MaxNum
    FROM
      object_classes
    LIMIT
      iCounter, 1;
    SELECT count(*)
    INTO
      @iMaxClassSpawn
    FROM
      object_spawns
    WHERE
      Classname LIKE @Classname;
    IF (@MaxNum > @iMaxClassSpawn) THEN
      UPDATE object_classes
      SET
        MaxNum = @iMaxClassSpawn
      WHERE
        Classname = @Classname;
    END IF;
    SET iCounter = iCounter + 1;
  END WHILE;

END
$$

--
-- Definition for procedure pMain
--
DROP PROCEDURE IF EXISTS pMain$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pMain()
BEGIN

  DECLARE iSpawnNumVeh SMALLINT(3) DEFAULT 100;

  CALL pCleanup();
  CALL pFixMaxNum;

  SELECT sum(MaxNum)
  FROM
    object_classes
  INTO
    @iMaxNumTotal;
  IF (iSpawnNumVeh > @iMaxNumTotal) THEN
    SET iSpawnNumVeh = @iMaxNumTotal;
  END IF;

  WHILE (fGetVehCount() < iSpawnNumVeh)
  DO
    CALL pSpawn();
  END WHILE;

END
$$

--
-- Definition for procedure pSpawn
--
DROP PROCEDURE IF EXISTS pSpawn$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pSpawn()
BEGIN
  DECLARE bSpawned TINYINT(1) DEFAULT 0;
  DECLARE iLID     INT DEFAULT 0;

  WHILE (bSpawned = 0)
  DO

    SET iLID = LAST_INSERT_ID();

    INSERT INTO object_data (ObjectUID, Instance, Classname, Damage, CharacterID, Worldspace, Inventory, Hitpoints, Fuel, Datestamp)
    SELECT ot.ObjectUID
         , '1'
         , ot.Classname
         , ot.Damage
         , '0'
         , ot.Worldspace
         , '[]'
         , ot.Hitpoints
         , '0.05'
         , sysdate()
    FROM
      (SELECT oc.Classname
            , oc.Chance
            , oc.MaxNum
            , oc.Damage
            , oc.Hitpoints
            , os.ObjectUID
            , os.Worldspace
       FROM
         object_classes AS oc
       INNER JOIN object_spawns AS os
       ON oc.Classname = os.Classname
       ORDER BY
         rand()) AS ot
    WHERE
      NOT EXISTS (SELECT od.ObjectUID
                  FROM
                    object_data AS od
                  WHERE
                    ot.ObjectUID = od.ObjectUID)
      AND fGetClassCount(ot.Classname) < ot.MaxNum
      AND fGetSpawnFromChance(ot.Chance) = 1
    LIMIT
      1;

    IF (LAST_INSERT_ID() <> iLID) THEN
      SET bSpawned = 1;
    END IF;

  END WHILE;
END
$$

--
-- Definition for procedure pSpawnVehicles
--
DROP PROCEDURE IF EXISTS pSpawnVehicles$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE pSpawnVehicles()
BEGIN
 
    DECLARE iCurrentVehicles INT(4) DEFAULT 0;
    DECLARE loopCounter INT(4) DEFAULT 0;
    DECLARE iSpawnAttempts INT(4) DEFAULT 0;
    DECLARE iTotalClasses INT(4) DEFAULT 0;                 
 
    CALL pCleanup();
    CALL pFixMaxNum;
 
    SET iCurrentVehicles = fGetVehCount();
 
    SELECT COUNT(*)
                    INTO iTotalClasses
                    FROM object_classes;
 
    SELECT SUM(MaxNum) FROM object_classes INTO @iMaxNumTotal;
		/*SELECT 500 INTO @iMaxNumTotal;*/
    IF (iCurrentVehicles > @iMaxNumTotal) THEN
        SET iSpawnAttempts = @iMaxNumTotal - iCurrentVehicles;
    END IF;
 
 
 
 
    WHILE (loopCounter < iTotalClasses) DO
 
            SELECT Classname, Chance, MaxNum, Damage, MaxFuel, Inventory, Hitpoints
                        INTO @rsClassname, @rsChance, @rsMaxNum, @rsDamage, @rsMaxFuel, @rsInventory, @rsHitpoints
                        FROM object_classes
                        LIMIT loopCounter, 1;
 
            SET @initialClassCount = fGetClassCount(@rsClassname);
 
            IF (@initialClassCount < @rsMaxNum) THEN
 
                SET @classloop = 0;
                SET @attemptsAtClass = @rsMaxNum - @initialClassCount;
 
                WHILE (@classloop < @attemptsAtClass) DO
                    SET @luckyDip = fGetSpawnFromChance(@rsChance + (RAND() / 10000));
 
                    IF (@luckyDip = 1) THEN
 
                                SELECT ObjectUID, Worldspace
                                                INTO @spawnUID, @spawnWorldspace
                                                FROM object_spawns o
                                                WHERE Classname = @rsClassname AND NOT EXISTS (SELECT 1 FROM object_data e WHERE e.ObjectUID = o.ObjectUID)
                                                ORDER BY RAND()
                                                LIMIT 1;
 
                                SET @fuel = (FLOOR( (RAND()*@rsMaxFuel) * 10000) / 10000);
 
                                INSERT INTO object_data (ObjectUID, Instance, Landmark, Classname, Damage, CharacterID, Worldspace, Inventory, Hitpoints, Fuel, Datestamp)
                                                    VALUES (@spawnUID, '1', '0', @rsClassname, @rsDamage, '0', @spawnWorldspace, @rsInventory, @rsHitpoints, @fuel, SYSDATE());
                                                                                                                     
 
                    END IF;
                    SET @classloop = @classloop + 1;
                END WHILE;
            END IF;
        SET loopCounter = loopCounter + 1;
    END WHILE;
 
END
$$

--
-- Definition for function fGetClassCount
--
DROP FUNCTION IF EXISTS fGetClassCount$$
CREATE DEFINER = 'root'@'localhost'
FUNCTION fGetClassCount(`clname` VARCHAR(32))
  RETURNS smallint(3)
  READS SQL DATA
BEGIN

  DECLARE iClassCount SMALLINT(3) DEFAULT 0;

  SELECT count(*)
  INTO
    iClassCount
  FROM
    object_data
  WHERE
    Classname = clname;

  RETURN iClassCount;
END
$$

--
-- Definition for function fGetSpawnFromChance
--
DROP FUNCTION IF EXISTS fGetSpawnFromChance$$
CREATE DEFINER = 'root'@'localhost'
FUNCTION fGetSpawnFromChance(`chance` DOUBLE)
  RETURNS tinyint(1)
  NO SQL
BEGIN

  DECLARE bspawn TINYINT(1) DEFAULT 0;

  IF (rand() <= chance) THEN
    SET bspawn = 1;
  END IF;

  RETURN bspawn;

END
$$

--
-- Definition for function fGetVehCount
--
DROP FUNCTION IF EXISTS fGetVehCount$$
CREATE DEFINER = 'root'@'localhost'
FUNCTION fGetVehCount()
  RETURNS smallint(3)
  READS SQL DATA
BEGIN

  DECLARE iVehCount SMALLINT(3) DEFAULT 0;

  SELECT count(*)
  INTO
    iVehCount
  FROM
    object_data, object_classes
  WHERE
    object_data.Classname = object_classes.Classname;

  RETURN iVehCount;
END
$$

DELIMITER ;

-- 
-- Dumping data for table character_data
--
-- Table hivemind.character_data does not contain any data (it is empty)

-- 
-- Dumping data for table dbver
--
INSERT INTO dbver VALUES 
  (123);

-- 
-- Dumping data for table object_classes
--
INSERT INTO object_classes VALUES 
  ('V3S_Civ', 0.50000, 3, '0.75', '[]', '0.2', '[]'),
  ('Ikarus', 1.00000, 0, '0.21', '[]', '0.2', '[]'),
  ('Old_bike_TK_INS_EP1', 1.00000, 3, '0.05', '[]', '0.2', '[]'),
  ('Old_bike_TK_CIV_EP1', 0.50000, 10, '0.01', '[]', '0.2', '[]'),
  ('TT650_Civ', 1.00000, 0, '0.10', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('TT650_Ins', 1.00000, 0, '0.10', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('tractor', 0.70000, 6, '0.20', '[]', '0.2', '[]'),
  ('UH1H_DZ', 0.90000, 2, '0.90', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('ATV_CZ_EP1', 1.00000, 2, '0.15', '[]', '0.2', '[]'),
  ('Mi17_DZ', 0.50000, 1, '0', '[]', '0.2', '[]'),
  ('An2_TK_EP1', 1.00000, 0, '0.05', '[]', '0.2', '[]'),
  ('HMMWV_Ambulance_CZ_DES_EP1', 1.00000, 0, '0', '[]', '0.2', '[]'),
  ('policecar', 0.70000, 1, '0.80', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('ATV_US_EP1', 0.25000, 8, '0.30', '[["wheel_1_1_steering",0.1]]', '0.2', '[]'),
  ('PBX', 0.50000, 4, '0.10', '[]', '0.2', '[]'),
  ('Smallboat_1', 1.00000, 0, '0.03', '[]', '0.2', '[]'),
  ('Smallboat_2', 1.00000, 0, '0.10', '[]', '0.2', '[]'),
  ('S1203_TK_CIV_EP1', 1.00000, 0, '0.70', '[]', '0.2', '[]'),
  ('BAF_Offroad_W', 1.00000, 0, '0.8', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('hilux1_civil_3_open', 0.90000, 1, '0.33', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('car_hatchback', 1.00000, 0, '0.20', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('Volha_2_TK_CIV_EP1', 1.00000, 0, '0.50', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('Lada2', 1.00000, 0, '0.35', '[]', '0.2', '[]'),
  ('Ural_TK_CIV_EP1', 1.00000, 0, '0.85', '[["glass1",1],["glass2",0.4],["glass3",1],["glass4",0.4],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["wheel_1_3_steering",0.4],["wheel_2_3_steering",0.4],["wheel_1_2_steering",1],["wheel_2_2_steering",0.4],["motor",0.8],["sklo predni P",0.5],["karoserie",0.853],["palivo",0.5]]', '0.2', '[]'),
  ('car_sedan', 1.00000, 0, '0.25', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('AN2_DZ', 1.00000, 2, '0.90', '[]', '0.2', '[]'),
  ('AH6X_DZ', 0.90000, 1, '0.5', ' [["motor",1],["karoserie",1],["elektronika",0.8]]', '0.2', '[]'),
  ('BAF_Offroad_D', 1.00000, 0, '0', '[]', '0.2', '[]'),
  ('datsun1_civil_2_covered', 1.00000, 0, '0.40', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('SkodaGreen', 1.00000, 0, '0.40', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('UAZ_CDF', 0.35000, 6, '0.70', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('VWGolf', 0.90000, 8, '0.35', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('Ikarus_TK_CIV_EP1', 1.00000, 1, '0.2', '[]', '0.2', '[]'),
  ('datsun1_civil_1_open', 1.00000, 0, '0.3', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('SkodaBlue', 0.25000, 20, '0.3', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('Lada1_TK_CIV_EP1', 0.90000, 3, '0.4', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('hilux1_civil_1_open', 1.00000, 0, '0.6', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1]]', '0.2', '[]'),
  ('Lada2_TK_CIV_EP1', 1.00000, 0, '0.4', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('hilux1_civil_2_covered', 1.00000, 0, '0.4', '[]', '0.2', '[]'),
  ('UralCivil', 0.70000, 3, '0.75', '[["glass1",1],["glass2",0.4],["glass3",1],["glass4",0.4],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["wheel_1_3_steering",0.4],["wheel_2_3_steering",0.4],["wheel_1_2_steering",1],["wheel_2_2_steering",0.4],["motor",0.8],["sklo predni P",0.5],["karoserie",0.853],["palivo",0.5]]', '0.2', '[]'),
  ('M1030_US_DES_EP1', 0.50000, 2, '0.4', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('Volha_1_TK_CIV_EP1', 1.00000, 0, '0.3', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('LandRover_TK_CIV_EP1', 0.50000, 1, '0.8', '[["glass1",1],["glass2",0.4],["glass3",1],["glass4",0.4],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["wheel_1_3_steering",0.4],["wheel_2_3_steering",0.4],["wheel_1_2_steering",1],["wheel_2_2_steering",0.4],["motor",0.8],["sklo predni P",0.5],["karoserie",0.853],["palivo",0.5]]', '0.2', '[]'),
  ('LadaLM', 1.00000, 0, '0.5', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0.2', '[]'),
  ('Lada1', 1.00000, 0, '0.4', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('UAZ_Unarmed_UN_EP1', 1.00000, 1, '0.7', '[["glass1",1],["glass2",0.4],["glass3",1],["glass4",0.4],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["wheel_1_3_steering",0.4],["wheel_2_3_steering",0.4],["wheel_1_2_steering",1],["wheel_2_2_steering",0.4],["motor",0.8],["sklo predni P",0.5],["karoserie",0.853],["palivo",0.5]]', '0.2', '[]'),
  ('Ural_INS', 1.00000, 0, '0.8', '[["glass1",1],["glass2",0.4],["glass3",1],["glass4",0.4],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["wheel_1_3_steering",0.4],["wheel_2_3_steering",0.4],["wheel_1_2_steering",1],["wheel_2_2_steering",0.4],["motor",0.8],["sklo predni P",0.5],["karoserie",0.853],["palivo",0.5]]', '0.2', '[]'),
  ('Land_A_Hospital', 1.00000, 5, '0', '[]', '0', NULL),
  ('Land_A_FuelStation_Feed', 1.00000, 0, '0', '[]', '0', NULL),
  ('Land_Mil_ControlTower', 1.00000, 1, '0', '[]', '0', NULL),
  ('Land_A_Crane_02b', 1.00000, 0, '0', '[]', '0', NULL),
  ('Land_A_GeneralStore_01', 1.00000, 0, '0', '[]', '0', NULL),
  ('Land_A_GeneralStore_01a', 1.00000, 16, '0', '[]', '0', NULL),
  ('Land_Shed_Ind02', 1.00000, 3, '0', '[]', '0', NULL),
  ('Land_Mil_Guardhouse', 1.00000, 1, '0', '[]', '0', NULL),
  ('Land_Mil_Barracks_i', 1.00000, 4, '0', '[]', '0', NULL),
  ('Old_moto_TK_Civ_EP1', 0.50000, 6, '.10', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('Mi17_Civilian_DZ', 1.00000, 0, '0', '[]', '.2', '[]'),
  ('TT650_TK_EP1', 1.00000, 0, '0', '[["wheel_1_1_steering",1]]', '0.2', '[]'),
  ('SUV_TK_EP1', 1.00000, 1, '0.1', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '0', NULL),
  ('HMMWV_DES_EP1_DZ', 1.00000, 0, '.1', '[["motor",0.8],["karoserie",1],["palivo",0.8],["wheel_1_1_steering",1],["wheel_2_1_steering",1],["sklo predni P",1],["glass1",1],["glass3",1]]', '.5', '[]'),
  ('S1203_ambulance_EP1', 1.00000, 0, '.1', '[]', '0', NULL),
  ('VolhaLimo_TK_CIV_EP1 ', 1.00000, 0, '.2', '[]', '0.2', '[]'),
  ('Fishing_Boat', 0.90000, 1, '0.2', '[]', '0.2', '[]');

-- 
-- Dumping data for table object_data
--
-- Table hivemind.object_data does not contain any data (it is empty)

-- 
-- Dumping data for table object_spawns
--
INSERT INTO object_spawns VALUES 
  ('1', 'Land_Mil_Barracks_i', '[180,[12214.938, 17758.033,0]]', ' Enterable Barracks Cabo Santa Lucia 1'),
  ('2', 'Land_Mil_Barracks_i', '[180,[12215.99, 17736.205,0]]', ' Enterable Barracks Cabo Santa Lucia 2'),
  ('3', 'Land_Mil_Barracks_i', '[270,[12113.604, 17549.924,0]]', ' Enterable Barracks Cabo Santa Lucia 3'),
  ('4', 'Land_Mil_Barracks_i', '[270,[12128.973, 17549.895,0]]', ' Enterable Barracks Cabo Santa Lucia 4'),
  ('5', 'Land_A_Hospital', '[270,[12106.365, 17752.197,0]]', ' Enterable Barracks Cabo Santa Lucia 4'),
  ('6', 'AH6', '[270,[12140.685, 17729.875,0]]', ' Enterable Barracks Cabo Santa Lucia 4'),
  ('7', 'Land_Shed_Ind02', '[90,[12512.091, 17698.373,0]]', ' Industrial Shed 1 Strip Mine'),
  ('8', 'Land_Mil_Guardhouse', '[90,[12091.051, 17624.527,0]]', ' Enterable Barracks Cabo Santa Lucia 3'),
  ('9', 'Land_Shed_Ind02', '[90,[12512.078, 17709.75,0]]', ' Industrial Shed 2 Strip Mine'),
  ('10', 'Land_Shed_Ind02', '[90,[12512.058, 17721.072,0]]', ' Industrial Shed 3 Strip Mine'),
  ('11', 'Land_A_GeneralStore_01a', '[305,[12499.264, 14903.036,0]]', ' Market Esponia'),
  ('12', 'Land_A_GeneralStore_01a', '[280,[17369.279, 14201.62,0]]', ' Market Masbete'),
  ('13', 'Land_A_GeneralStore_01a', '[100,[18932.539, 13970.487,0]]', ' Market Pita'),
  ('14', 'Land_A_Hospital', '[220,[18830.082, 14205.258,0]]', ' Hospital Pita'),
  ('15', 'Land_Mil_ControlTower', '[312,[19253.377, 13880.749,0]]', ' ACT Pita Airfield'),
  ('16', 'Land_A_GeneralStore_01a', '[92,[14102.422, 12533.236,0]]', ' Market Bagango Delete a Poss. Move'),
  ('17', 'Land_A_Hospital', '[350,[14058.509, 12469.194,0]]', ' Hospital Bagango'),
  ('18', 'AH6X_DZ', '[0,[9840.2432, 9957.749,0]]', ' Paraiso AH6 Spawn 1'),
  ('19', 'AH6X_DZ', '[270,[9696.9473, 9804.5547,0]]', ' Paraiso AH6 Spawn 2'),
  ('20', 'AH6X_DZ', '[0,[9874.8291, 9982.8799,0]]', ' Paraiso AH6 Spawn 3'),
  ('21', 'AH6X_DZ', '[0,[10379.663, 10139.93,0]]', ' Paraiso AH6 Spawn 4'),
  ('22', 'AH6X_DZ', '[0,[9255.8135, 10144.221,0]]', ' Paraiso AH6 Spawn 5'),
  ('23', 'AH6X_DZ', '[0,[9392.167, 9971.4531,0]]', ' Paraiso AH6 Spawn 6'),
  ('24', 'AH6X_DZ', '[40,[19226.57, 13891.751,0]]', ' Pita AH6 Spawn 1'),
  ('25', 'AH6X_DZ', '[40,[19285.365, 13887.885,0]]', ' Pita AH6 Spawn 2'),
  ('26', 'AH6X_DZ', '[40,[19268.947, 13903.275,0]]', ' Pita AH6 Spawn 3'),
  ('27', 'AH6X_DZ', '[40,[18640.467, 14511.408,0]]', ' Pita AH6 Spawn 4'),
  ('28', 'AH6X_DZ', '[40,[19130.715, 13957.444,0]]', ' Pita AH6 Spawn 5'),
  ('29', 'AH6X_DZ', '[40,[18976.715, 14217.056,0]]', ' Pita AH6 Spawn 6'),
  ('30', 'AH6X_DZ', '[175,[18201.971, 17994.227,0]]', ' Antigua AH6 Spawn 1'),
  ('31', 'AH6X_DZ', '[175,[18022.094, 18837.639,0]]', ' Antigua AH6 Spawn 2'),
  ('32', 'AH6X_DZ', '[175,[17740.158, 18293.775,0]]', ' Antigua AH6 Spawn 3'),
  ('33', 'AH6X_DZ', '[175,[17304.639, 17912.613,0]]', ' Antigua AH6 Spawn 4'),
  ('34', 'AH6X_DZ', '[195,[12012.314, 15462.838,0]]', ' Pesadas AH6 Spawn 1'),
  ('35', 'AH6X_DZ', '[195,[11912.08, 15447.997,0]]', ' Pesadas AH6 Spawn 2'),
  ('36', 'AH6X_DZ', '[195,[11958.771, 15365.646,0]]', ' Pesadas AH6 Spawn 3'),
  ('37', 'AH6X_DZ', '[195,[11847.103, 15296.562,0]]', ' Pesadas AH6 Spawn 4'),
  ('38', 'AH6X_DZ', '[0,[4912.7061, 15473.937,0]]', ' Isla del Vida AH6 Spawn 1'),
  ('39', 'AH6X_DZ', '[0,[4955.9854, 15747.413,0]]', ' Isla del Vida AH6 Spawn 2'),
  ('40', 'AH6X_DZ', '[355,[4980.5352, 16075.607,0]]', ' Isla del Vida AH6 Spawn 3'),
  ('41', 'AH6X_DZ', '[45,[4417.8525, 15806.573,0]]', ' Isla del Vassal AH6 Spawn 1'),
  ('42', 'AH6X_DZ', '[45,[4421.7549, 15556.715,0]]', ' Isla del Vassal AH6 Spawn 2'),
  ('43', 'AH6X_DZ', '[150,[4575.2319, 15274.136,0]]', ' Isla del Vassal AH6 Spawn 3'),
  ('44', 'AH6X_DZ', '[185,[2549.7756, 2990.8325,0]]', ' Rahmadi AH6 Spawn 1'),
  ('45', 'AH6X_DZ', '[230,[3131.946, 2728.2703,0]]', ' Rahmadi AH6 Spawn 2'),
  ('46', 'AH6X_DZ', '[255,[2907.343, 2836.1133,0]]', ' Rahmadi AH6 Spawn 3'),
  ('47', 'AH6X_DZ', '[255,[7641.6875, 6246.3926,0]]', ' Arcadi AH6 Spawn 1'),
  ('48', 'UH1H_DZ', '[0,[9768.0215, 9965.8379,0]]', ' Paraiso UH1 Spawn 1'),
  ('49', 'UH1H_DZ', '[0,[9961.668, 9983.123,0]]', ' Paraiso UH1 Spawn 2'),
  ('50', 'UH1H_DZ', '[0,[9255.793, 10021.686,0]]', ' Paraiso UH1 Spawn 3'),
  ('51', 'UH1H_DZ', '[270,[9671.8457, 9804.8936,0]]', ' Paraiso UH1 Spawn 4'),
  ('52', 'UH1H_DZ', '[180,[9585.0273, 9819.3047,0]]', ' Paraiso UH1 Spawn 5'),
  ('53', 'UH1H_DZ', '[180,[2753.8005, 2672.1826,0]]', ' Rahmadi UH1 Spawn 1'),
  ('54', 'UH1H_DZ', '[125,[2921.6829, 3057.4292,0]]', ' Rahmadi UH1 Spawn 5'),
  ('55', 'UH1H_DZ', '[245,[4938.4893, 15473.471,0]]', ' Isla del Vida UH1 Spawn 1'),
  ('56', 'UH1H_DZ', '[75,[4908.8252, 15834.633,0]]', ' Isla del Vida UH1 Spawn 2'),
  ('57', 'UH1H_DZ', '[75,[5411.083, 15765.569,0]]', ' Isla del Vida UH1 Spawn 3'),
  ('58', 'UH1H_DZ', '[75,[4555.3745, 15290.068,0]]', ' Isla del Vassal UHi Spawn 1'),
  ('59', 'UH1H_DZ', '[75,[4488.6772, 15483.641,0]]', ' Isla del Vassal UH1 Spawn 2'),
  ('60', 'UH1H_DZ', '[75,[4391.8174, 15808.56,0]]', ' Isla del Vassal UH1 Spawn 3'),
  ('61', 'UH1H_DZ', '[105,[11874.796, 15371.278,0]]', ' Pesadas UH1 Spawn 1'),
  ('62', 'UH1H_DZ', '[185,[11871.795, 15482.457,0]]', ' Pesadas UH1 Spawn 2'),
  ('63', 'UH1H_DZ', '[290,[11997.843, 15418.979,0]]', ' Pesadas UH1 Spawn 3'),
  ('64', 'UH1H_DZ', '[290,[11944.572, 15296.531,0]]', ' Pesadas UH1 Spawn 4'),
  ('65', 'UH1H_DZ', '[290,[11832.779, 15285.64,0]]', ' Pesadas UH1 Spawn 5'),
  ('66', 'UH1H_DZ', '[0,[12406.447, 17468.381,0]]', ' Cabo Santa Lucia UH1 Spawn 1'),
  ('67', 'UH1H_DZ', '[0,[12140.722, 17757.068,0]]', ' Cabo Santa Lucia UH1 Spawn 2'),
  ('68', 'UH1H_DZ', '[0,[12202.939, 17547.191,0]]', ' Cabo Santa Lucia UH1 Spawn 3'),
  ('69', 'UH1H_DZ', '[0,[12090.093, 17750.174,0]]', ' Cabo Santa Lucia UH1 Spawn 4'),
  ('70', 'UH1H_DZ', '[0,[12064.701, 17675.529,0]]', ' Cabo Santa Lucia UH1 Spawn 5'),
  ('71', 'UH1H_DZ', '[0,[12512.527, 17672.982,0]]', ' Cabo Santa Lucia UH1 Spawn 6'),
  ('72', 'AH6X_DZ', '[270,[12077.461, 17635.549,0]]', ' Cabo Santa Lucia AH6 Spawn 1'),
  ('73', 'AH6X_DZ', '[0,[12140.348, 17549.396,0]]', ' Cabo Santa Lucia AH6 Spawn 2'),
  ('74', 'AH6X_DZ', '[0,[12209.184, 17631.158,0]]', ' Cabo Santa Lucia AH6 Spawn 3'),
  ('75', 'AH6X_DZ', '[0,[12072.036, 17725.236,0]]', ' Cabo Santa Lucia AH6 Spawn 4'),
  ('76', 'AH6X_DZ', '[0,[12140.965, 17707.445,0]]', ' Cabo Santa Lucia AH6 Spawn 5'),
  ('77', 'UH1H_DZ', '[270,[18176.949, 18094.736,0]]', ' Antigua UH1 Spawn 1'),
  ('78', 'UH1H_DZ', '[270,[17399.58, 17974.721,0]]', ' Antigua UH1 Spawn 2'),
  ('79', 'UH1H_DZ', '[270,[17936.225, 18415.6,0]]', ' Antigua UH1 Spawn 3'),
  ('80', 'UH1H_DZ', '[270,[18057.014, 18672.379,0]]', ' Antigua UH1 Spawn 4'),
  ('81', 'UH1H_DZ', '[270,[17878.91, 18163.469,0]]', ' Antigua UH1 Spawn 5'),
  ('82', 'UH1H_DZ', '[45,[19202.479, 13916.8,0]]', ' Pita UH1 Spawn 1'),
  ('83', 'UH1H_DZ', '[315,[19307.605, 13894.47,0]]', ' Pita UH1 Spawn 2'),
  ('84', 'UH1H_DZ', '[315,[19291.564, 13944.055,0]]', ' Pita UH1 Spawn 3'),
  ('85', 'UH1H_DZ', '[40,[19093.432, 14121.464,0]]', ' Pita UH1 Spawn 4'),
  ('86', 'UH1H_DZ', '[40,[18675.594, 14483.003,0]]', ' Pita UH1 Spawn 5'),
  ('87', 'UH1H_DZ', '[90,[2543.7949, 2539.1309,0]]', ' Rahmadi UH1 Spawn 2'),
  ('88', 'UH1H_DZ', '[35,[3050.2959, 2648.313,0]]', ' Rahmadi UH1 Spawn 3'),
  ('89', 'UH1H_DZ', '[125,[3364.74, 2921.0156,0]]', ' Rahmadi UH1 Spawn 4'),
  ('90', 'Mi17_DZ', '[0,[2539.6934, 2925.6006,0]]', ' Rahmadi Mi17 Spawn 1'),
  ('91', 'Mi17_DZ', '[35,[3007.8516, 2577.4023,0]]', ' Rahmadi Mi17 Spawn 2'),
  ('92', 'Mi17_DZ', '[0,[2549.3755, 2416.5479,0]]', ' Rahmadi Mi17 Spawn 3'),
  ('93', 'Mi17_DZ', '[0,[3336.8044, 2426.283,0]]', ' Rahmadi Mi17 Spawn 4'),
  ('94', 'Mi17_DZ', '[345,[18081.51, 18565.043,0]]', ' Antigua Mi17 Spawn 1'),
  ('95', 'Mi17_DZ', '[345,[18157.979, 18183.965,0]]', ' Antigua Mi17 Spawn 2'),
  ('96', 'Mi17_DZ', '[345,[17490.604, 18228.338,0]]', ' Antigua Mi17 Spawn 3'),
  ('97', 'Mi17_DZ', '[345,[18305.705, 18085.648,0]]', ' Antigua Mi17 Spawn 4'),
  ('98', 'Mi17_DZ', '[0,[12105.221, 17664.307,0]]', ' Cabo Santa Lucia Mi17 Spawn 1'),
  ('99', 'Mi17_DZ', '[0,[12068.168, 17571.033,0]]', ' Cabo Santa Lucia Mi17 Spawn 2'),
  ('100', 'Mi17_DZ', '[0,[12206.876, 17479.082,0]]', ' Cabo Santa Lucia Mi17 Spawn 3'),
  ('101', 'Mi17_DZ', '[230,[12321.407, 17563.324,0]]', ' Cabo Santa Lucia Mi17 Spawn 3'),
  ('102', 'Mi17_DZ', '[230,[12452.358, 17640.217,0]]', ' Cabo Santa Lucia Mi17 Spawn 4'),
  ('103', 'Mi17_DZ', '[230,[12582.212, 17756.256,0]]', ' Cabo Santa Lucia Mi17 Spawn 5'),
  ('104', 'Mi17_DZ', '[290,[11886.513, 15285.516,0]]', ' Pesadas Mi17 Spawn 1'),
  ('105', 'Mi17_DZ', '[10,[11939.032, 15397.446,0]]', ' Pesadas Mi17 Spawn 2'),
  ('106', 'Mi17_DZ', '[10,[11988.927, 15395.191,0]]', ' Pesadas Mi17 Spawn 3'),
  ('107', 'Mi17_DZ', '[10,[11958.975, 15443.094,0]]', ' Pesadas Mi17 Spawn 4'),
  ('108', 'Mi17_DZ', '[10,[11888.932, 15453.461,0]]', ' Pesadas Mi17 Spawn 5'),
  ('109', 'Mi17_DZ', '[10,[19311.402, 14004.939,0]]', ' Pita Mi17 Spawn 1'),
  ('110', 'Mi17_DZ', '[10,[19011.9, 14311.271,0]]', ' Pita Mi17 Spawn 2'),
  ('111', 'Mi17_DZ', '[10,[18739.82, 14425.946,0]]', ' Pita Mi17 Spawn 3'),
  ('112', 'Mi17_DZ', '[10,[19357.648, 13783.67,0]]', ' Pita Mi17 Spawn 4'),
  ('113', 'Mi17_DZ', '[310,[19154.393, 14065.777,0]]', ' Pita Mi17 Spawn 5'),
  ('114', 'Mi17_DZ', '[310,[8189.0264, 16992.965,0]]', ' Selva Outpost Mi17 Spawn 1'),
  ('115', 'Mi17_DZ', '[310,[8213.5244, 17071.598,0]]', ' Selva Outpost Mi17 Spawn 2'),
  ('116', 'AH6X_DZ', '[230,[8206.0469, 17038.66,0]]', ' Selva Outpost AH6 Spawn 1'),
  ('117', 'AH6X_DZ', '[20,[8230.9854, 17029.168,0]]', ' Selva Outpost AH6 Spawn 2'),
  ('118', 'AH6X_DZ', '[310,[8191.4106, 17022.541,0]]', ' Selva Outpost AH6 Spawn 3'),
  ('119', 'AH6X_DZ', '[310,[8175.7061, 16941.83,0]]', ' Selva Outpost AH6 Spawn 4'),
  ('120', 'AH6X_DZ', '[300,[8216.2393, 17051.885,0]]', ' Selva Outpost AH6 Spawn 5'),
  ('121', 'UH1H_DZ', '[310,[8165.166, 17043.479,0]]', ' Selva Outpost UH1 Spawn 1'),
  ('122', 'UH1H_DZ', '[20,[8151.2959, 17012.453,0]]', ' Selva Outpost UH1 Spawn 2'),
  ('123', 'UH1H_DZ', '[290,[8128.8682, 16966.361,0]]', ' Selva Outpost UH1 Spawn 3'),
  ('124', 'V3S_Civ', '[270,[9566.6875, 9805.5547,0]]', ' Paraiso V3S Spawn 1'),
  ('125', 'V3S_Civ', '[0,[9661.5605, 9784.1172,0]]', ' Paraiso V3S Spawn 2'),
  ('126', 'V3S_Civ', '[0,[9528.8047, 9874.7939,0]]', ' Paraiso V3S Spawn 3'),
  ('127', 'V3S_Civ', '[90,[9909.6787, 9984.1904,0]]', ' Paraiso V3S Spawn 4'),
  ('128', 'V3S_Civ', '[0,[9805.2256, 9945.9912,0]]', ' Paraiso V3S Spawn 5'),
  ('129', 'V3S_Civ', '[300,[8160.0557, 17069.096,0]]', ' Selva Outpost V3S Spawn 1'),
  ('130', 'V3S_Civ', '[300,[8140.1768, 17030.285,0]]', ' Selva Outpost V3S Spawn 2'),
  ('131', 'V3S_Civ', '[300,[9546.8701, 16754.477,0]]', ' Selva Outpost V3S Spawn 3'),
  ('132', 'V3S_Civ', '[325,[7720.3872, 17796.422,0]]', ' Selva Outpost V3S Spawn 3'),
  ('133', 'V3S_Civ', '[300,[8209.7559, 17182.902,0]]', ' Selva Outpost V3S Spawn 4'),
  ('134', 'V3S_Civ', '[280,[11692.708, 17931.594,0]]', ' Cabo Santa Lucia V3S Spawn 1'),
  ('135', 'V3S_Civ', '[0,[12538.753, 17710.385,0]]', ' Cabo Santa Lucia V3S Spawn 2'),
  ('136', 'V3S_Civ', '[270,[12116.866, 17697.303,0]]', ' Cabo Santa Lucia V3S Spawn 3'),
  ('137', 'V3S_Civ', '[90,[12247.991, 17480.262,0]]', ' Cabo Santa Lucia V3S Spawn 4'),
  ('138', 'V3S_Civ', '[270,[12240.018, 17629.609,0]]', ' Cabo Santa Lucia V3S Spawn 5'),
  ('139', 'V3S_Civ', '[130,[19125.521, 13940.723,0]]', ' Pita V3S Spawn 1'),
  ('140', 'V3S_Civ', '[155,[19015.824, 14104.756,0]]', ' Pita V3S Spawn 2'),
  ('141', 'V3S_Civ', '[40,[19212.961, 13884.933,0]]', ' Pita V3S Spawn 3'),
  ('142', 'V3S_Civ', '[40,[19293.623, 13855.5,0]]', ' Pita V3S Spawn 4'),
  ('143', 'V3S_Civ', '[140,[18612.602, 14463.818,0]]', ' Pita V3S Spawn 5'),
  ('144', 'V3S_Civ', '[55,[4894.5459, 15498.271,0]]', ' Isla del Vida V3S Spawn 1'),
  ('145', 'V3S_Civ', '[15,[4910.3657, 15451.239,0]]', ' Isla del Vida V3S Spawn 2'),
  ('146', 'V3S_Civ', '[55,[4883.2437, 15564.367,0]]', ' Isla del Vida V3S Spawn 3'),
  ('147', 'V3S_Civ', '[55,[4514.5884, 15291.074,0]]', ' Isla del Vassal V3S Spawn 1'),
  ('148', 'V3S_Civ', '[55,[4530.4971, 15272.057,0]]', ' Isla del Vassal V3S Spawn 2'),
  ('149', 'V3S_Civ', '[275,[4584.6328, 15281.092,0]]', ' Isla del Vassal V3S Spawn 3'),
  ('150', 'V3S_Civ', '[278,[11919.425, 15261.576,0]]', ' Pesadas V3S Spawn 1'),
  ('151', 'V3S_Civ', '[15,[12001.418, 15355.454,0]]', ' Pesadas V3S Spawn 2'),
  ('152', 'V3S_Civ', '[195,[11975.27, 15470.835,0]]', ' Pesadas V3S Spawn 3'),
  ('153', 'V3S_Civ', '[94,[11930.256, 15460.736,0]]', ' Pesadas V3S Spawn 4'),
  ('154', 'V3S_Civ', '[180,[11862.666, 15484.654,0]]', ' Pesadas V3S Spawn 5'),
  ('155', 'UAZ_CDF', '[0,[9888.3135, 9993.9668,0]]', ' Paraiso UAZ Spawn 01'),
  ('156', 'UAZ_CDF', '[0,[9546.0752, 9819.8643,0]]', ' Paraiso UAZ Spawn 02'),
  ('157', 'UAZ_CDF', '[0,[9374.2188, 9973.1455,0]]', ' Paraiso UAZ Spawn 03'),
  ('158', 'UAZ_CDF', '[270,[9040.5439, 9752.5342,0]]', ' Paraiso UAZ Spawn 04'),
  ('159', 'UAZ_CDF', '[0,[8670.9531, 10105.245,0]]', ' Paraiso UAZ Spawn 05'),
  ('160', 'UAZ_CDF', '[170,[9393.6035, 10885.151,0]]', ' Paraiso UAZ Spawn 06'),
  ('161', 'UAZ_CDF', '[0,[10267.567, 10062.299,0]]', ' Paraiso UAZ Spawn 07'),
  ('162', 'UAZ_CDF', '[140,[11744.879, 10236.215,0]]', ' Paraiso UAZ Spawn 08'),
  ('163', 'UAZ_CDF', '[30,[11102.648, 9853.1816,0]]', ' Paraiso UAZ Spawn 09'),
  ('164', 'UAZ_CDF', '[30,[10403.922, 9768.0029,0]]', ' Paraiso UAZ Spawn 10'),
  ('165', 'UAZ_CDF', '[0,[4382.959, 15352.326,0]]', ' Isla del Vassal UAZ Spawn 1'),
  ('166', 'UAZ_CDF', '[0,[4527.1357, 15304.811,0]]', ' Isla del Vassal UAZ Spawn 2'),
  ('167', 'UAZ_CDF', '[260,[4508.7686, 15523.982,0]]', ' Isla del Vassal UAZ Spawn 3'),
  ('168', 'UAZ_CDF', '[260,[4282.6636, 15758.173,0]]', ' Isla del Vassal UAZ Spawn 4'),
  ('169', 'UAZ_CDF', '[40,[4636.4204, 15762.74,0]]', ' Isla del Vassal UAZ Spawn 5'),
  ('170', 'UAZ_CDF', '[40,[4899.8999, 15477.756,0]]', ' Isla del Vida UAZ Spawn 1'),
  ('171', 'UAZ_CDF', '[5,[4938.8486, 15756.64,0]]', ' Isla del Vida UAZ Spawn 2'),
  ('172', 'UAZ_CDF', '[90,[4940.6685, 15826.856,0]]', ' Isla del Vida UAZ Spawn 3'),
  ('173', 'UAZ_CDF', '[305,[4950.8857, 16043.738,0]]', ' Isla del Vida UAZ Spawn 4'),
  ('174', 'UAZ_CDF', '[185,[5074.8735, 15611.265,0]]', ' Isla del Vida UAZ Spawn 5'),
  ('175', 'UAZ_CDF', '[20,[8169.3164, 16967.785,0]]', ' Selva Outpost UAZ Spawn 1'),
  ('176', 'UAZ_CDF', '[20,[8101.0322, 16977.215,0]]', ' Selva Outpost UAZ Spawn 2'),
  ('177', 'UAZ_CDF', '[105,[11852.596, 15388.551,0]]', ' Pesadas UAZ Spawn 01'),
  ('178', 'UAZ_CDF', '[105,[11914.395, 15491.206,0]]', ' Pesadas UAZ Spawn 02'),
  ('179', 'UAZ_CDF', '[5,[11704.211, 15462.591,0]]', ' Pesadas UAZ Spawn 03'),
  ('180', 'UAZ_CDF', '[110,[11808.661, 15067.004,0]]', ' Pesadas UAZ Spawn 04'),
  ('181', 'UAZ_CDF', '[110,[12072.247, 15831.567,0]]', ' Pesadas UAZ Spawn 05'),
  ('182', 'UAZ_CDF', '[10,[12477.049, 15446.208,0]]', ' Pesadas UAZ Spawn 06'),
  ('183', 'UAZ_CDF', '[95,[12250.482, 14895.874,0]]', ' Pesadas UAZ Spawn 07'),
  ('184', 'UAZ_CDF', '[120,[11192.342, 14598.487,0]]', ' Pesadas UAZ Spawn 08'),
  ('185', 'UAZ_CDF', '[120,[10400.504, 15047.329,0]]', ' Pesadas UAZ Spawn 09'),
  ('186', 'UAZ_CDF', '[85,[12849.287, 15853.391,0]]', ' Pesadas UAZ Spawn 10'),
  ('187', 'UAZ_CDF', '[90,[12067.305, 17790.977,0]]', ' Cabo Snta Lucia UAZ Spawn 01'),
  ('188', 'UAZ_CDF', '[90,[12073.452, 17613.244,0]]', ' Cabo Snta Lucia UAZ Spawn 02'),
  ('189', 'UAZ_CDF', '[90,[12417.367, 17440.354,0]]', ' Cabo Snta Lucia UAZ Spawn 03'),
  ('190', 'UAZ_CDF', '[90,[12486.919, 17663.492,0]]', ' Cabo Snta Lucia UAZ Spawn 04'),
  ('191', 'UAZ_CDF', '[0,[11164.637, 16950.809,0]]', ' Cabo Snta Lucia UAZ Spawn 05'),
  ('192', 'UAZ_CDF', '[270,[11119.385, 16258.02,0]]', ' Cabo Snta Lucia UAZ Spawn 06'),
  ('193', 'UAZ_CDF', '[340,[11933.774, 17944.188,0]]', ' Cabo Snta Lucia UAZ Spawn 07'),
  ('194', 'UAZ_CDF', '[160,[13135.588, 17808.186,0]]', ' Cabo Snta Lucia UAZ Spawn 08'),
  ('195', 'UAZ_CDF', '[145,[11496.587, 17280.512,0]]', ' Cabo Snta Lucia UAZ Spawn 09'),
  ('196', 'UAZ_CDF', '[320,[11281.665, 17610.881,0]]', ' Cabo Snta Lucia UAZ Spawn 10'),
  ('197', 'UAZ_CDF', '[320,[17544.617, 14398.367,0]]', ' Pita UAZ Spawn 01'),
  ('198', 'UAZ_CDF', '[75,[17883.352, 14556.688,0]]', ' Pita UAZ Spawn 02'),
  ('199', 'UAZ_CDF', '[155,[18661.609, 14614.479,0]]', ' Pita UAZ Spawn 03'),
  ('200', 'UAZ_CDF', '[70,[19003.441, 14107.715,0]]', ' Pita UAZ Spawn 04'),
  ('201', 'UAZ_CDF', '[30,[19195.965, 13894.599,0]]', ' Pita UAZ Spawn 05'),
  ('202', 'UAZ_CDF', '[0,[19204.117, 13672.519,0]]', ' Pita UAZ Spawn 06'),
  ('203', 'UAZ_CDF', '[105,[19480.641, 13607.707,0]]', ' Pita UAZ Spawn 07'),
  ('204', 'UAZ_CDF', '[180,[17711.525, 12439.023,0]]', ' Tres Valles UAZ Spawn 08'),
  ('205', 'UAZ_CDF', '[180,[17178.879, 13600.937,0]]', ' Pita UAZ Spawn 09'),
  ('206', 'UAZ_CDF', '[295,[15645.564, 13859.689,0]]', ' Pita UAZ Spawn 10'),
  ('207', 'UAZ_CDF', '[280,[2920.2893, 2855.238,0]]', ' Rahmadi UAZ Spawn 1'),
  ('208', 'UAZ_CDF', '[320,[3129.4175, 2707.439,0]]', ' Rahmadi UAZ Spawn 2'),
  ('209', 'UAZ_CDF', '[65,[2712.4189, 2062.5293,0]]', ' Rahmadi UAZ Spawn 3'),
  ('210', 'UAZ_CDF', '[0,[17733.623, 12362.439,0]]', ' Tres Valles UAZ Spawn 1'),
  ('211', 'UAZ_CDF', '[0,[17870.922, 12370.672,0]]', ' Tres Valles UAZ Spawn 2'),
  ('212', 'UAZ_CDF', '[0,[17706.645, 12311.967,0]]', ' Tres Valles UAZ Spawn 3'),
  ('213', 'UAZ_CDF', '[0,[18820.953, 13696.659,0]]', ' Pita W Outpost UAZ Spawn 1'),
  ('214', 'V3S_Civ', '[0,[18846.859, 13706.691,0]]', ' Pita W Outpost V3S Spawn 1'),
  ('215', 'V3S_Civ', '[0,[17527.439, 9530.5361,0]]', ' Everone W Outpost V3S Spawn 1'),
  ('216', 'V3S_Civ', '[270,[17596.648, 9551.3477,0]]', ' Everone W Outpost V3S Spawn 2'),
  ('217', 'V3S_Civ', '[270,[16480.42, 8886.9492,0]]', ' Everone W Outpost V3S Spawn 3'),
  ('218', 'V3S_Civ', '[0,[17744.859, 12373.82,0]]', ' Tres Valles V3S Spawn 1'),
  ('219', 'V3S_Civ', '[305,[17468.957, 12661.32,0]]', ' Tres Valles V3S Spawn 2'),
  ('220', 'V3S_Civ', '[270,[17777.047, 12377.736,0]]', ' Tres Valles V3S Spawn 3'),
  ('221', 'UAZ_CDF', '[180,[17546.502, 9550.4121,0]]', ' Everone W Outpost UAZ Spawn 1'),
  ('222', 'UAZ_CDF', '[180,[17607.625, 9534.0615,0]]', ' Everone W Outpost UAZ Spawn 2'),
  ('223', 'UAZ_CDF', '[125,[17680.918, 9591.6934,0]]', ' Everone W Outpost UAZ Spawn 3'),
  ('224', 'UAZ_CDF', '[305,[18722.082, 13573.166,0]]', ' Pita W Outpost UAZ Spawn 2'),
  ('225', 'UAZ_CDF', '[35,[18800.354, 13643.576,0]]', ' Pita W Outpost UAZ Spawn 3'),
  ('226', 'UAZ_CDF', '[35,[18809.715, 13636.333,0]]', ' Pita W Outpost V3S Spawn 2'),
  ('227', 'Mi17_Civilian', '[35,[18865.184, 14314.302,0]]', ' Civilian Mi17 Test'),
  ('228', 'AN2_DZ', '[310,[19261.957, 13971.961,0]]', ' Pita An2 Civilian Spawn 1'),
  ('229', 'An2_1_TK_CIV_EP1', '[130,[18652.947, 14499.781,0]]', ' Pita An2 Civilian Spawn 2'),
  ('230', 'C130J_US_EP1', '[0,[9256.1035, 10070.821,0]]', ' Paraiso C130 Spawn 1'),
  ('231', 'C130J_US_EP1', '[270,[10329.604, 10143.598,0]]', ' Paraiso C130 Spawn 2'),
  ('232', 'AN2_DZ', '[0,[2537.0405, 2448.8245,0]]', ' Rahmadi An2 Civilian Spawn 1'),
  ('233', 'An2_1_TK_CIV_EP1', '[180,[2549.0581, 2886.7957,0]]', ' Rahmadi An2 Civilian Spawn 2'),
  ('234', 'An2_1_TK_CIV_EP1', '[165,[18026.404, 18803.309,0]]', ' Antigua An2 Civilian Spawn 1'),
  ('235', 'An2_1_TK_CIV_EP1', '[340,[18189.279, 18038.754,0]]', ' Antigua An2 Civilian Spawn 2'),
  ('236', 'SkodaBlue', '[45,[2856.6646, 2879.707,0]]', ' Rahmadi Blue Car Spawn 2'),
  ('237', 'SkodaBlue', '[45,[2867.4851, 2904.7437,0]]', ' Rahmadi Blue Car Spawn 1'),
  ('238', 'SkodaBlue', '[60,[2869.9722, 2419.9805,0]]', ' Rahmadi Blue Car Spawn 3'),
  ('239', 'SkodaBlue', '[260,[9374.7178, 5125.0571,0]]', ' Tiberia Blue Car Spawn 3'),
  ('240', 'ATV_US_EP1', '[345,[17380.547, 18263.604,0]]', ' Antigua ATV Spawn 1'),
  ('241', 'ATV_US_EP1', '[150,[18014.412, 17992.965,0]]', ' Antigua ATV Spawn 2'),
  ('242', 'ATV_US_EP1', '[195,[18184.555, 17830.195,0]]', ' Antigua ATV Spawn 3'),
  ('243', 'ATV_US_EP1', '[195,[17861.482, 18907.068,0]]', ' Antigua ATV Spawn 4'),
  ('244', 'ATV_US_EP1', '[145,[12259.225, 18245.035,0]]', ' Cabo Santa Lucia ATV Spawn 1'),
  ('245', 'ATV_US_EP1', '[90,[12872.783, 17840.301,0]]', ' Cabo Santa Lucia ATV Spawn 2'),
  ('246', 'ATV_US_EP1', '[90,[11591.126, 17731.512,0]]', ' Cabo Santa Lucia ATV Spawn 3'),
  ('247', 'ATV_US_EP1', '[60,[12652.463, 17989.709,0]]', ' Cabo Santa Lucia ATV Spawn 4'),
  ('248', 'ATV_US_EP1', '[275,[12271.709, 17503.91,0]]', ' Cabo Santa Lucia ATV Spawn 5'),
  ('249', 'ATV_US_EP1', '[70,[10939.354, 17032.869,0]]', ' Isla De Vicotr ATV Spawn 1'),
  ('250', 'ATV_US_EP1', '[165,[11312.984, 16910.756,0]]', ' Isla De Vicotr ATV Spawn 2'),
  ('251', 'ATV_US_EP1', '[90,[10578.36, 16362.319,0]]', ' Mataredo ATV Spawn 1'),
  ('252', 'ATV_US_EP1', '[290,[10684.803, 16155.376,0]]', ' Mataredo ATV Spawn 2'),
  ('253', 'ATV_US_EP1', '[185,[10500.597, 16140.455,0]]', ' Mataredo ATV Spawn 3'),
  ('254', 'ATV_US_EP1', '[0,[10244.028, 15973.882,0]]', ' Mataredo ATV Spawn 4'),
  ('255', 'ATV_US_EP1', '[290,[8230.4336, 17044.904,0]]', ' Selva Outpost ATV Spawn 1'),
  ('256', 'ATV_US_EP1', '[10,[8398.4688, 17270.848,0]]', ' Selva Outpost ATV Spawn 2'),
  ('257', 'ATV_US_EP1', '[280,[8194.8945, 17330.188,0]]', ' Selva Outpost ATV Spawn 3'),
  ('258', 'ATV_US_EP1', '[280,[7578.4678, 15669.787,0]]', ' Hunapa ATV Spawn 1'),
  ('259', 'ATV_US_EP1', '[10,[7698.6597, 15897.414,0]]', ' Hunapa ATV Spawn 2'),
  ('260', 'ATV_US_EP1', '[185,[7753.5742, 15614.903,0]]', ' Hunapa ATV Spawn 3'),
  ('261', 'ATV_US_EP1', '[95,[10253.148, 15784.257,0]]', ' Passo Paradiso ATV Spawn 1'),
  ('262', 'ATV_US_EP1', '[95,[10404.459, 15809.559,0]]', ' Passo Paradiso ATV Spawn 2'),
  ('263', 'ATV_US_EP1', '[95,[9890.7656, 15509.824,0]]', ' Passo Paradiso ATV Spawn 3'),
  ('264', 'ATV_US_EP1', '[325,[10836.721, 15402.855,0]]', ' Pesadas ATV Spawn 1'),
  ('265', 'ATV_US_EP1', '[245,[11457.726, 15529.814,0]]', ' Pesadas ATV Spawn 2'),
  ('266', 'ATV_US_EP1', '[0,[11633.342, 15447.198,0]]', ' Pesadas ATV Spawn 3'),
  ('267', 'ATV_US_EP1', '[85,[11728.162, 15459.257,0]]', ' Pesadas ATV Spawn 4'),
  ('268', 'ATV_US_EP1', '[105,[11835.16, 15313.992,0]]', ' Pesadas ATV Spawn 5'),
  ('269', 'ATV_US_EP1', '[185,[12384.061, 15624.061,0]]', ' Pesadas ATV Spawn 6'),
  ('270', 'ATV_US_EP1', '[95,[11444.766, 15064.48,0]]', ' Pesadas ATV Spawn 7'),
  ('271', 'ATV_US_EP1', '[270,[12357.455, 14935.483,0]]', ' Eponia ATV Spawn 1'),
  ('272', 'ATV_US_EP1', '[90,[12378.846, 15252.655,0]]', ' Eponia ATV Spawn 2'),
  ('273', 'ATV_US_EP1', '[0,[12533.046, 15033.469,0]]', ' Eponia ATV Spawn 3'),
  ('274', 'ATV_US_EP1', '[155,[12723.672, 14910.354,0]]', ' Eponia ATV Spawn 4'),
  ('275', 'ATV_US_EP1', '[90,[12512.755, 14993.653,0]]', ' Eponia ATV Spawn 5'),
  ('276', 'ATV_US_EP1', '[30,[12641.361, 14976.99,0]]', ' Eponia ATV Spawn 6'),
  ('277', 'ATV_US_EP1', '[30,[14006.19, 16465.65,0]]', ' PIco de Rev ATV Spawn 1'),
  ('278', 'ATV_US_EP1', '[41,[13922.67, 16677.576,0]]', ' PIco de Rev ATV Spawn 2'),
  ('279', 'ATV_US_EP1', '[345,[13771.832, 17067.785,0]]', ' PIco de Rev ATV Spawn 3'),
  ('280', 'ATV_US_EP1', '[185,[13343.394, 15961.805,0]]', ' PIco de Rev ATV Spawn 4'),
  ('281', 'ATV_US_EP1', '[5,[13984.737, 15727.688,0]]', ' PIco de Rev ATV Spawn 5'),
  ('282', 'ATV_US_EP1', '[310,[14856.045, 16172.146,0]]', ' PIco de Rev ATV Spawn 6'),
  ('283', 'ATV_US_EP1', '[270,[11331.332, 14567.011,0]]', ' Tandag ATV Spawn 2'),
  ('284', 'ATV_US_EP1', '[140,[11173.348, 14598.836,0]]', ' Tandag ATV Spawn 2'),
  ('285', 'ATV_US_EP1', '[10,[11441.637, 14859.672,0]]', ' Tandag ATV Spawn 3'),
  ('286', 'ATV_US_EP1', '[140,[11523.901, 14431.365,0]]', ' Tandag ATV Spawn 4'),
  ('287', 'ATV_US_EP1', '[200,[10625.654, 14166.037,0]]', ' Tandag ATV Spawn 5'),
  ('288', 'ATV_US_EP1', '[70,[11770.543, 14359.137,0]]', ' Tandag ATV Spawn 6'),
  ('289', 'ATV_US_EP1', '[190,[9689.4385, 14493.54,0]]', ' Pacamac ATV Spawn 1'),
  ('290', 'ATV_US_EP1', '[305,[9130.6465, 14841.538,0]]', ' Pacamac ATV Spawn 2'),
  ('291', 'ATV_US_EP1', '[305,[8716.4443, 15105.802,0]]', ' Pacamac ATV Spawn 3'),
  ('292', 'ATV_US_EP1', '[160,[9699.7969, 14397.961,0]]', ' Pacamac ATV Spawn 4'),
  ('293', 'ATV_US_EP1', '[160,[9813.2412, 14570.07,0]]', ' Pacamac ATV Spawn 5'),
  ('294', 'ATV_US_EP1', '[160,[9895.1699, 14397.479,0]]', ' Pacamac ATV Spawn 5'),
  ('295', 'ATV_US_EP1', '[190,[10096.514, 14111.26,0]]', ' Tlaloc ATV Spawn 1'),
  ('296', 'ATV_US_EP1', '[170,[10462.068, 13900.223,0]]', ' Tlaloc ATV Spawn 2'),
  ('297', 'ATV_US_EP1', '[170,[10545.517, 13506.027,0]]', ' Tlaloc ATV Spawn 3'),
  ('298', 'ATV_US_EP1', '[225,[10564.691, 13006.662,0]]', ' Tlaloc ATV Spawn 4'),
  ('299', 'ATV_US_EP1', '[190,[10826.713, 12616.553,0]]', ' Tlaloc ATV Spawn 5'),
  ('300', 'ATV_US_EP1', '[315,[10908.372, 12561.295,0]]', ' Tlaloc ATV Spawn 6'),
  ('301', 'ATV_US_EP1', '[260,[11588.313, 12133.002,0]]', ' Mercalillo ATV Spawn 1'),
  ('302', 'ATV_US_EP1', '[70,[12171.41, 11460.012,0]]', ' Mercalillo ATV Spawn 2'),
  ('303', 'ATV_US_EP1', '[355,[12160.645, 11723.408,0]]', ' Mercalillo ATV Spawn 3'),
  ('304', 'ATV_US_EP1', '[70,[12932.066, 11645.485,0]]', ' Mercalillo ATV Spawn 4'),
  ('305', 'ATV_US_EP1', '[350,[13192.123, 11492.268,0]]', ' Mercalillo ATV Spawn 5'),
  ('306', 'ATV_US_EP1', '[0,[13771.916, 11487.947,0]]', ' Mercalillo ATV Spawn 6'),
  ('307', 'ATV_US_EP1', '[15,[14715.434, 10725.323,0]]', ' Obregan ATV Spawn 1'),
  ('308', 'ATV_US_EP1', '[290,[13331.195, 10686.248,0]]', ' Obregan ATV Spawn 2'),
  ('309', 'ATV_US_EP1', '[265,[13430.641, 11061.036,0]]', ' Obregan ATV Spawn 3'),
  ('310', 'ATV_US_EP1', '[325,[13731.513, 10641.496,0]]', ' Obregan ATV Spawn 4'),
  ('311', 'ATV_US_EP1', '[315,[14767.403, 11201.049,0]]', ' Obregan ATV Spawn 5'),
  ('312', 'ATV_US_EP1', '[50,[14298.314, 10929.199,0]]', ' Obregan ATV Spawn 6'),
  ('313', 'ATV_US_EP1', '[0,[13732.793, 11869.204,0]]', ' Bagango ATV Spawn 1'),
  ('314', 'ATV_US_EP1', '[30,[14173.046, 11874.826,0]]', ' Bagango ATV Spawn 2'),
  ('315', 'ATV_US_EP1', '[165,[14621.995, 11875.805,0]]', ' Bagango ATV Spawn 3'),
  ('316', 'ATV_US_EP1', '[340,[12535.565, 12691.447,0]]', ' Bagango ATV Spawn 4'),
  ('317', 'ATV_US_EP1', '[275,[13113.127, 13466.992,0]]', ' Bagango ATV Spawn 5'),
  ('318', 'ATV_US_EP1', '[350,[14022.95, 12895.669,0]]', ' Bagango ATV Spawn 6'),
  ('319', 'ATV_US_EP1', '[350,[15357.152, 13783.643,0]]', ' Benoma ATV Spawn 1'),
  ('320', 'ATV_US_EP1', '[310,[15324.236, 14102.392,0]]', ' Benoma ATV Spawn 2'),
  ('321', 'ATV_US_EP1', '[110,[14750.63, 13959.395,0]]', ' Benoma ATV Spawn 3'),
  ('322', 'ATV_US_EP1', '[250,[14329.94, 13331.594,0]]', ' Benoma ATV Spawn 4'),
  ('323', 'ATV_US_EP1', '[250,[15423.657, 12771.717,0]]', ' Benoma ATV Spawn 6'),
  ('324', 'ATV_US_EP1', '[315,[16875.299, 14351.316,0]]', ' Masbete ATV Spawn 1'),
  ('325', 'ATV_US_EP1', '[85,[17170.316, 13573.194,0]]', ' Masbete ATV Spawn 2'),
  ('326', 'ATV_US_EP1', '[325,[16511.139, 13863.115,0]]', ' Masbete ATV Spawn 3'),
  ('327', 'ATV_US_EP1', '[0,[17379.035, 14098.071,0]]', ' Masbete ATV Spawn 4'),
  ('328', 'ATV_US_EP1', '[180,[17746.787, 12423.521,0]]', ' Masbete ATV Spawn 5'),
  ('329', 'ATV_US_EP1', '[280,[17086.889, 14114.72,0]]', ' Masbete ATV Spawn 6'),
  ('330', 'ATV_US_EP1', '[280,[18788.313, 13699.436,0]]', ' Pita ATV Spawn 1'),
  ('331', 'ATV_US_EP1', '[270,[19233.328, 13621.528,0]]', ' Pita ATV Spawn 2'),
  ('332', 'ATV_US_EP1', '[220,[19149.684, 13973.387,0]]', ' Pita ATV Spawn 3'),
  ('333', 'ATV_US_EP1', '[220,[19373.244, 13329.306,0]]', ' Pita ATV Spawn 4'),
  ('334', 'ATV_US_EP1', '[85,[18752.859, 14053.574,0]]', ' Pita ATV Spawn 5'),
  ('335', 'ATV_US_EP1', '[85,[18319.543, 14585.994,0]]', ' Pita ATV Spawn 6'),
  ('336', 'ATV_US_EP1', '[170,[16457.686, 9407.3047,0]]', ' Everon ATV Spawn 1'),
  ('337', 'ATV_US_EP1', '[355,[17559.357, 9527.668,0]]', ' Everon ATV Spawn 2'),
  ('338', 'ATV_US_EP1', '[355,[17462.969, 9747.5684,0]]', ' Everon ATV Spawn 3'),
  ('339', 'ATV_US_EP1', '[60,[17248.268, 9492.6846,0]]', ' Everon ATV Spawn 4'),
  ('340', 'ATV_US_EP1', '[60,[16130.468, 9387.7676,0]]', ' Everon ATV Spawn 5'),
  ('341', 'ATV_US_EP1', '[310,[16441.422, 9273.0723,0]]', ' Everon ATV Spawn 6'),
  ('342', 'ATV_US_EP1', '[310,[14392.932, 9453.4658,0]]', ' Modesto ATV Spawn 1'),
  ('343', 'ATV_US_EP1', '[180,[14207.552, 9275.4639,0]]', ' Modesto ATV Spawn 2'),
  ('344', 'ATV_US_EP1', '[200,[15578.814, 8790.1211,0]]', ' Modesto ATV Spawn 3'),
  ('345', 'ATV_US_EP1', '[295,[14161.967, 8306.5127,0]]', ' Modesto ATV Spawn 4'),
  ('346', 'ATV_US_EP1', '[90,[13884.359, 10308.657,0]]', ' Modesto ATV Spawn 5'),
  ('347', 'ATV_US_EP1', '[90,[15390.302, 9845.292,0]]', ' Modesto ATV Spawn 6'),
  ('348', 'ATV_US_EP1', '[270,[13559.581, 9748.7197,0]]', ' Corazol ATV Spawn 03'),
  ('349', 'ATV_US_EP1', '[195,[13486.236, 10258.578,0]]', ' Corazol ATV Spawn 01'),
  ('350', 'ATV_US_EP1', '[195,[13275.942, 9896.4834,0]]', ' Corazol ATV Spawn 02'),
  ('351', 'ATV_US_EP1', '[95,[12944.86, 9021.8037,0]]', ' Corazol Spawn ATV 05'),
  ('352', 'ATV_US_EP1', '[180,[13233.57, 9197.9199,0]]', ' Corazol Spawn 06'),
  ('353', 'ATV_US_EP1', '[180,[13537.303, 8705.9971,0]]', ' Corazol ATV Spawn 05'),
  ('354', 'ATV_US_EP1', '[305,[12959.085, 8615.1406,0]]', ' Corazol ATV Spawn 06'),
  ('355', 'ATV_US_EP1', '[270,[13527.632, 7769.0684,0]]', ' Corazol ATV Spawn 07'),
  ('356', 'ATV_US_EP1', '[85,[12330.675, 8502.3789,0]]', ' Corazol ATV Spawn 08'),
  ('357', 'ATV_US_EP1', '[225,[12776.792, 8088.4609,0]]', ' Corazol ATV Spawn 09'),
  ('358', 'ATV_US_EP1', '[225,[13068.459, 7779.9375,0]]', ' Corazol ATV Spawn 10'),
  ('359', 'ATV_US_EP1', '[355,[9935.2119, 9995.6387,0]]', ' Paraizo ATV Spawn 1'),
  ('360', 'ATV_US_EP1', '[265,[9584.291, 9918.0068,0]]', ' Paraizo ATV Spawn 2'),
  ('361', 'ATV_US_EP1', '[265,[9074.3545, 10031.754,0]]', ' Paraizo ATV Spawn 3'),
  ('362', 'ATV_US_EP1', '[50,[8275.6904, 9556.4492,0]]', ' Paraizo ATV Spawn 4'),
  ('363', 'ATV_US_EP1', '[190,[8631.5781, 10087.42,0]]', ' Paraizo ATV Spawn 5'),
  ('364', 'ATV_US_EP1', '[190,[10265.806, 9102.2021,0]]', ' Paraizo ATV Spawn 6'),
  ('365', 'ATV_US_EP1', '[190,[10836.935, 10762.635,0]]', ' Paraizo ATV Spawn 7'),
  ('366', 'ATV_US_EP1', '[270,[10707.213, 8931.9424,0]]', ' Paraizo ATV Spawn 8'),
  ('367', 'ATV_US_EP1', '[270,[10376.319, 8797.7979,0]]', ' Paraizo ATV Spawn 9'),
  ('368', 'ATV_US_EP1', '[90,[9279.1406, 8486.5117,0]]', ' Samato ATV Spawn 1'),
  ('369', 'ATV_US_EP1', '[0,[9755.3975, 8928.5938,0]]', ' Samato ATV Spawn 2'),
  ('370', 'ATV_US_EP1', '[333,[9673.2314, 8729.3877,0]]', ' Samato ATV Spawn 3'),
  ('371', 'ATV_US_EP1', '[325,[7769.2363, 9713.6895,0]]', ' Samato ATV Spawn 6'),
  ('372', 'ATV_US_EP1', '[170,[8062.3921, 9325.2705,0]]', ' Samato ATV Spawn 5'),
  ('373', 'ATV_US_EP1', '[75,[7364.7051, 8713.5742,0]]', ' Samato ATV Spawn 7'),
  ('374', 'ATV_US_EP1', '[180,[6735.6646, 8053.2725,0]]', ' Samato ATV Spawn 7'),
  ('375', 'ATV_US_EP1', '[180,[8147.7485, 9030.5508,0]]', ' Samato ATV Spawn 8'),
  ('376', 'ATV_US_EP1', '[10,[7326.9194, 8076.7896,0]]', ' Samato ATV Spawn 8'),
  ('377', 'ATV_US_EP1', '[155,[7749.5542, 8445.165,0]]', ' Samato ATV Spawn 9'),
  ('378', 'ATV_US_EP1', '[330,[7028.0518, 7549.6768,0]]', ' Samato ATV Spawn 10'),
  ('379', 'ATV_US_EP1', '[272,[7992.5854, 7757.7383,0]]', ' Race Track ATV Spawn 01'),
  ('380', 'ATV_US_EP1', '[90,[8174.9712, 7796.0557,0]]', ' Race Track ATV Spawn 02'),
  ('381', 'ATV_US_EP1', '[90,[8175.0313, 7786.3804,0]]', ' Race Track ATV Spawn 03'),
  ('382', 'ATV_US_EP1', '[180,[8227.2891, 7757.6758,0]]', ' Race Track ATV Spawn 04'),
  ('383', 'ATV_US_EP1', '[180,[8224.7012, 7757.7222,0]]', ' Race Track ATV Spawn 05'),
  ('384', 'ATV_US_EP1', '[180,[7703.1064, 7488.0542,0]]', ' Race Track ATV Spawn 06'),
  ('385', 'ATV_US_EP1', '[35,[7605.3423, 7615.3833,0]]', ' Race Track ATV Spawn 07'),
  ('386', 'ATV_US_EP1', '[115,[7784.7666, 7243.9541,0]]', ' Race Track ATV Spawn 08'),
  ('387', 'ATV_US_EP1', '[30,[8286.7441, 7330.126,0]]', ' Race Track ATV Spawn 09'),
  ('388', 'ATV_US_EP1', '[290,[8179.3335, 7410.4541,0]]', ' Race Track ATV Spawn 10'),
  ('389', 'ATV_US_EP1', '[270,[8922.0479, 6116.8076,0]]', ' Cayo ATV Spawn 1'),
  ('390', 'ATV_US_EP1', '[90,[7455.0259, 6510.6494,0]]', ' Cayo ATV Spawn 2'),
  ('391', 'ATV_US_EP1', '[250,[7552.7539, 6379.6768,0]]', ' Cayo ATV Spawn 3'),
  ('392', 'ATV_US_EP1', '[65,[9245.2412, 5383.667,0]]', ' Cayo ATV Spawn 4'),
  ('393', 'ATV_US_EP1', '[140,[9716.8838, 6651.0176,0]]', ' Cayo ATV Spawn 5'),
  ('394', 'ATV_US_EP1', '[140,[9224.9209, 5863.1211,0]]', ' Cayo ATV Spawn 6'),
  ('395', 'ATV_US_EP1', '[270,[10212.307, 6389.4199,0]]', ' Cayo ATV Spawn 8'),
  ('396', 'ATV_US_EP1', '[50,[10612.569, 4731.2642,0]]', ' Iguana ATV Spawn 2'),
  ('397', 'ATV_US_EP1', '[350,[10765.535, 4908.606,0]]', ' Iguana ATV Spawn 3'),
  ('398', 'ATV_US_EP1', '[0,[10759.62, 4727.9126,0]]', ' Iguana ATV Spawn 3'),
  ('399', 'ATV_US_EP1', '[95,[10457.897, 4846.4717,0]]', ' Iguana ATV Spawn 1'),
  ('400', 'ATV_US_EP1', '[220,[10639.32, 5166.2607,0]]', ' Iguana ATV Spawn 4'),
  ('401', 'ATV_US_EP1', '[140,[11208.929, 5173.5142,0]]', ' Iguana ATV Spawn 5'),
  ('402', 'ATV_US_EP1', '[0,[11443.593, 5430.6909,0]]', ' Iguana ATV Spawn 6'),
  ('403', 'ATV_US_EP1', '[265,[11802.5, 5855.7676,0]]', ' Dolores ATV Spawn 1'),
  ('404', 'ATV_US_EP1', '[0,[11218.14, 5882.2227,0]]', ' Dolores ATV Spawn 2'),
  ('405', 'ATV_US_EP1', '[0,[11549.52, 6211.8594,0]]', ' Dolores ATV Spawn 3'),
  ('406', 'ATV_US_EP1', '[180,[11226.982, 6169.1431,0]]', ' Dolores ATV Spawn 4'),
  ('407', 'ATV_US_EP1', '[180,[11914.789, 6117.499,0]]', ' Dolores ATV Spawn 5'),
  ('408', 'ATV_US_EP1', '[225,[11727.537, 6335.4551,0]]', ' Dolores ATV Spawn 6'),
  ('409', 'ATV_US_EP1', '[265,[11822.31, 7090.0234,0]]', ' Ortego ATV Spawn 1'),
  ('410', 'ATV_US_EP1', '[265,[11913.512, 7392.7637,0]]', ' Ortego ATV Spawn 2'),
  ('411', 'ATV_US_EP1', '[175,[12552.689, 7298.541,0]]', ' Ortego ATV Spawn 3'),
  ('412', 'ATV_US_EP1', '[80,[12183.152, 7055.9189,0]]', ' Ortego ATV Spawn 4'),
  ('413', 'ATV_US_EP1', '[315,[12264.061, 7437.9043,0]]', ' Ortego ATV Spawn 5'),
  ('414', 'ATV_US_EP1', '[20,[12624.957, 7491.2817,0]]', ' Ortego ATV Spawn 6'),
  ('415', 'ATV_US_EP1', '[20,[2855.4546, 2855.3638,0]]', ' Rahmadi ATV Spawn 1'),
  ('416', 'ATV_US_EP1', '[180,[3133.9897, 2747.3169,0]]', ' Rahmadi ATV Spawn 2'),
  ('417', 'ATV_US_EP1', '[310,[2962.665, 2948.0823,0]]', ' Rahmadi ATV Spawn 3'),
  ('418', 'Tractor', '[330,[16718.453, 9483.3604,0]]', ' Everon Tractor Spawn 1'),
  ('419', 'Tractor', '[130,[16437.078, 9294.0234,0]]', ' Everon Tractor Spawn 2'),
  ('420', 'Tractor', '[300,[16096.494, 9383.6465,0]]', ' Everon Tractor Spawn 3'),
  ('421', 'Tractor', '[150,[16040.936, 9493.1719,0]]', ' Everon Tractor Spawn 4'),
  ('422', 'Tractor', '[315,[16658.113, 9195.6494,0]]', ' Everon Tractor Spawn 5'),
  ('423', 'Tractor', '[145,[16058.27, 9290.8359,0]]', ' Everon Tractor Spawn 6'),
  ('424', 'Tractor', '[145,[15987.362, 9351.708,0]]', ' Everon Tractor Spawn 7'),
  ('425', 'Tractor', '[280,[16661.479, 9601.1934,0]]', ' Everon Tractor Spawn 8'),
  ('426', 'Tractor', '[20,[16706.117, 8962.1016,0]]', ' Everon Tractor Spawn 9'),
  ('427', 'Tractor', '[120,[15575.993, 8784.9893,0]]', ' Everon Tractor Spawn 2'),
  ('428', 'Tractor', '[220,[15548.715, 8748.3887,0]]', ' Everon Tractor Spawn 3'),
  ('429', 'Tractor', '[85,[15665.043, 8675.502,0]]', ' Everon Tractor Spawn 4'),
  ('430', 'Tractor', '[85,[15502.667, 9053.0352,0]]', ' Everon Tractor Spawn 4'),
  ('431', 'Tractor', '[85,[15550.704, 9364.5938,0]]', ' Everon Tractor Spawn 5'),
  ('432', 'Tractor', '[85,[14067.707, 9137.8066,0]]', ' Modesta Tractor Spawn 1'),
  ('433', 'Tractor', '[335,[14290.978, 9257.0117,0]]', ' Modesta Tractor Spawn 2'),
  ('434', 'Tractor', '[205,[14175.877, 9404.9277,0]]', ' Modesta Tractor Spawn 3'),
  ('435', 'Tractor', '[320,[14139.916, 9321.6592,0]]', ' Modesta Tractor Spawn 4'),
  ('436', 'Tractor', '[0,[14217.781, 9290.1963,0]]', ' Modesta Tractor Spawn 5'),
  ('437', 'Tractor', '[65,[14162.084, 9450.7402,0]]', ' Modesta Tractor Spawn 6'),
  ('438', 'CAA1_AH6_NAPA', '[65,[14064.463, 9997.1436,0]]', ' Modesta Tractor Spawn 6'),
  ('439', 'Tractor', '[65,[13480.425, 11084.865,0]]', ' Mercailillo Tractor Spawn 1'),
  ('440', 'Tractor', '[75,[13841.589, 10873.508,0]]', ' Mercailillo Tractor Spawn 2'),
  ('441', 'Tractor', '[310,[13377.789, 10725.222,0]]', ' Mercailillo Tractor Spawn 3'),
  ('442', 'Tractor', '[185,[13567.765, 9732.2803,0]]', ' Mercailillo Tractor Spawn 4'),
  ('443', 'Tractor', '[325,[13449.932, 9749.0898,0]]', ' Mercailillo Tractor Spawn 5'),
  ('444', 'Tractor', '[165,[13745.217, 10610.709,0]]', ' Mercailillo Tractor Spawn 6'),
  ('445', 'Tractor', '[10,[13892.892, 10303.744,0]]', ' Mercailillo Tractor Spawn 7'),
  ('446', 'Tractor', '[60,[9078.6289, 5317.2021,0]]', ' Tiberia Tactor Spawn 1'),
  ('447', 'Tractor', '[0,[9244.0039, 5258.2129,0]]', ' Tiberia Tactor Spawn 2'),
  ('448', 'Tractor', '[310,[9233.5654, 5402.3545,0]]', ' Tiberia Tactor Spawn 5'),
  ('449', 'Tractor', '[90,[9510.1602, 5291.814,0]]', ' Tiberia Tactor Spawn 6'),
  ('450', 'Tractor', '[310,[11263.881, 5310.6763,0]]', ' Parato Tactor Spawn 1'),
  ('451', 'Tractor', '[15,[11455.899, 5441.3906,0]]', ' Parato Tactor Spawn 2'),
  ('452', 'Tractor', '[160,[11196.919, 5193.4238,0]]', ' Parato Tactor Spawn 3'),
  ('453', 'Tractor', '[135,[11211.378, 5387.3389,0]]', ' Parato Tactor Spawn 4'),
  ('454', 'Tractor', '[310,[11389.01, 5467.2998,0]]', ' Parato Tactor Spawn 5'),
  ('455', 'Tractor', '[310,[11461.543, 5567.4204,0]]', ' Parato Tactor Spawn 6'),
  ('456', 'Tractor', '[245,[8948.9141, 7754.7988,0]]', ' Gulan Tactor Spawn 1'),
  ('457', 'Tractor', '[345,[8932.4521, 7711.4063,0]]', ' Gulan Tactor Spawn 2'),
  ('458', 'Tractor', '[5,[8114.6514, 7773.7998,0]]', ' Gulan Tactor Spawn 3'),
  ('459', 'Tractor', '[240,[9655.4014, 8718.3398,0]]', ' Gulan Tactor Spawn 4'),
  ('460', 'Tractor', '[65,[9550.2715, 8663.8438,0]]', ' Gulan Tactor Spawn 5'),
  ('461', 'Tractor', '[5,[9777.8447, 8927.7578,0]]', ' Gulan Tactor Spawn 6'),
  ('462', 'Tractor', '[320,[9757.5615, 8390.9287,0]]', ' Gulan Tactor Spawn 7'),
  ('463', 'Tractor', '[90,[9202.1758, 5095.1836,0]]', ' Tiberia Tactor Spawn 3'),
  ('464', 'Tractor', '[85,[9371.1123, 5312.4634,0]]', ' Tiberia Tactor Spawn 4'),
  ('465', 'SkodaBlue', '[250,[7563.5112, 6287.1182,0]]', ' Arcadia Blue Car Spawn 5'),
  ('466', 'SkodaBlue', '[155,[7642.9409, 6298.7144,0]]', ' Arcadia Blue Car Spawn 2'),
  ('467', 'SkodaBlue', '[155,[7665.3184, 6298.2163,0]]', ' Arcadia Blue Car Spawn 4'),
  ('468', 'SkodaBlue', '[165,[7729.7134, 6308.3081,0]]', ' Arcadia Blue Car Spawn 3'),
  ('469', 'SkodaBlue', '[255,[7742.7593, 6253.5107,0]]', ' Arcadia Blue Car Spawn 1'),
  ('470', 'SkodaBlue', '[290,[7614.0444, 6618.0679,0]]', ' Arcadia Blue Car Spawn 6'),
  ('471', 'SkodaBlue', '[185,[7502.1567, 6531.5503,0]]', ' Arcadia Blue Car Spawn 7'),
  ('472', 'SkodaBlue', '[0,[8912.6455, 6111.417,0]]', ' Cayo Blue Car Spawn 1'),
  ('473', 'SkodaBlue', '[185,[9267.8008, 5891.6187,0]]', ' Cayo Blue Car Spawn 2'),
  ('474', 'SkodaBlue', '[270,[9433.9453, 5815.3887,0]]', ' Cayo Blue Car Spawn 4'),
  ('475', 'SkodaBlue', '[125,[9377.4805, 5803.4731,0]]', ' Cayo Blue Car Spawn 3'),
  ('476', 'SkodaBlue', '[270,[9304.6641, 5953.9004,0]]', ' Cayo Blue Car Spawn 5'),
  ('477', 'SkodaBlue', '[180,[9268.8623, 5256.2656,0]]', ' Tiberia Blue Car Spawn 1'),
  ('478', 'SkodaBlue', '[345,[9304.0107, 5230.3125,0]]', ' Tiberia Blue Car Spawn 2'),
  ('479', 'SkodaBlue', '[120,[10618.417, 4738.5879,0]]', ' Iguana Blue Car Spawn 1'),
  ('480', 'SkodaBlue', '[20,[10543.868, 4802.7974,0]]', ' Iguana Blue Car Spawn 2'),
  ('481', 'SkodaBlue', '[180,[10756.826, 4916.188,0]]', ' Iguana Blue Car Spawn 3'),
  ('482', 'SkodaBlue', '[90,[10710.458, 5064.814,0]]', ' Iguana Blue Car Spawn 5'),
  ('483', 'SkodaBlue', '[90,[10763.692, 4975.6826,0]]', ' Iguana Blue Car Spawn 4'),
  ('484', 'SkodaBlue', '[0,[11266.196, 5230.6924,0]]', ' Parata Blue Car Spawn 1'),
  ('485', 'SkodaBlue', '[205,[11318.961, 5312.1108,0]]', ' Parata Blue Car Spawn 2'),
  ('486', 'SkodaBlue', '[0,[11272.54, 5937.249,0]]', ' Dolores Blue Car Spawn 1'),
  ('487', 'SkodaBlue', '[240,[11580.529, 5863.6816,0]]', ' Dolores Blue Car Spawn 2'),
  ('488', 'SkodaBlue', '[350,[11231.804, 6103.2827,0]]', ' Dolores Blue Car Spawn 3'),
  ('489', 'SkodaBlue', '[0,[11300.517, 6108.7964,0]]', ' Dolores Blue Car Spawn 4'),
  ('490', 'SkodaBlue', '[0,[11451.096, 6099.4961,0]]', ' Dolores Blue Car Spawn 5'),
  ('491', 'SkodaBlue', '[90,[12276.444, 6834.7388,0]]', ' Ortega Blue Car Spawn 1'),
  ('492', 'SkodaBlue', '[185,[12342.341, 7144.5981,0]]', ' Ortega Blue Car Spawn 2'),
  ('493', 'SkodaBlue', '[90,[12258.512, 7126.6123,0]]', ' Ortega Blue Car Spawn 3'),
  ('494', 'SkodaBlue', '[90,[12861.404, 6835.1855,0]]', ' Ortega Blue Car Spawn 4'),
  ('495', 'SkodaBlue', '[270,[12459.404, 7124.3848,0]]', ' Ortega Blue Car Spawn 5'),
  ('496', 'SkodaBlue', '[125,[12344.502, 7300.3057,0]]', ' Ortega Blue Car Spawn 6'),
  ('497', 'SkodaBlue', '[90,[13210.672, 6923.229,0]]', ' Geraldo Blue Car Spawn 1'),
  ('498', 'SkodaBlue', '[275,[13252.3, 6974.7437,0]]', ' Geraldo Blue Car Spawn 2'),
  ('499', 'SkodaBlue', '[100,[13406.417, 6896.7261,0]]', ' Geraldo Blue Car Spawn 3'),
  ('500', 'SkodaBlue', '[60,[11857.912, 7326.9946,0]]', ' Geraldo Blue Car Spawn 4'),
  ('501', 'SkodaBlue', '[280,[10762.789, 7354.1982,0]]', ' Vallejo Blue Car Spawn 1'),
  ('502', 'SkodaBlue', '[270,[8106.1387, 7787.8442,0]]', ' Gulan Blue Care Spawn 1'),
  ('503', 'SkodaBlue', '[270,[8093.269, 7770.5703,0]]', ' Gulan Blue Care Spawn 2'),
  ('504', 'SkodaBlue', '[180,[8179.5273, 7863.2739,0]]', ' Gulan Blue Care Spawn 3'),
  ('505', 'SkodaBlue', '[180,[6949.6538, 8253.6514,0]]', ' Estrella Blue Care Spawn 1'),
  ('506', 'SkodaBlue', '[0,[6794.9419, 8023.7607,0]]', ' Estrella Blue Care Spawn 2'),
  ('507', 'SkodaBlue', '[110,[6863.5786, 8198.332,0]]', ' Estrella Blue Care Spawn 3'),
  ('508', 'SkodaBlue', '[170,[7461.3823, 8800.8506,0]]', ' Cedras Blue Care Spawn 1'),
  ('509', 'SkodaBlue', '[350,[7471.2422, 8795.1895,0]]', ' Cedras Blue Care Spawn 2'),
  ('510', 'SkodaBlue', '[175,[7439.9785, 8921.123,0]]', ' Cedras Blue Care Spawn 3'),
  ('511', 'SkodaBlue', '[330,[7749.4028, 9147.0957,0]]', ' Ambergris Blue Care Spawn 1'),
  ('512', 'SkodaBlue', '[330,[7834.1738, 9195.8271,0]]', ' Ambergris Blue Care Spawn 2'),
  ('513', 'SkodaBlue', '[150,[7659.5835, 9007.3535,0]]', ' Ambergris Blue Care Spawn 3'),
  ('514', 'SkodaBlue', '[95,[8366.542, 9013.3809,0]]', ' Chantico Blue Care Spawn 1'),
  ('515', 'SkodaBlue', '[90,[8253.0293, 8904.4932,0]]', ' Chantico Blue Care Spawn 2'),
  ('516', 'SkodaBlue', '[90,[8107.2534, 9321.9531,0]]', ' Chantico Blue Care Spawn 3'),
  ('517', 'SkodaBlue', '[90,[8085.2783, 9345.835,0]]', ' Chantico Blue Care Spawn 4'),
  ('518', 'SkodaBlue', '[135,[8463.3574, 9432.0459,0]]', ' Chantico Blue Care Spawn 5'),
  ('519', 'SkodaBlue', '[330,[8216.5635, 9636.6172,0]]', ' Chantico Blue Care Spawn 6'),
  ('520', 'SkodaBlue', '[30,[8646.3125, 10059.145,0]]', ' Chantico Blue Care Spawn 7'),
  ('521', 'SkodaBlue', '[0,[8973.957, 8398.6084,0]]', ' Somato Blue Care Spawn 1'),
  ('522', 'SkodaBlue', '[265,[9240.2393, 8142.5918,0]]', ' Somato Blue Care Spawn 2'),
  ('523', 'SkodaBlue', '[265,[9231.5234, 8164.6133,0]]', ' Somato Blue Care Spawn 3'),
  ('524', 'SkodaBlue', '[5,[9191.5957, 8451.4297,0]]', ' Somato Blue Care Spawn 4'),
  ('525', 'SkodaBlue', '[60,[9784.3428, 8693.9785,0]]', ' Paraiso Blue Care Spawn 1'),
  ('526', 'SkodaBlue', '[105,[10181.584, 8416.8457,0]]', ' Paraiso Blue Care Spawn 2'),
  ('527', 'SkodaBlue', '[195,[10156.863, 8317.8672,0]]', ' Paraiso Blue Care Spawn 3'),
  ('528', 'SkodaBlue', '[0,[10646.906, 8963.9746,0]]', ' Paraiso Blue Care Spawn 4'),
  ('529', 'SkodaBlue', '[0,[10602.343, 8964.5107,0]]', ' Paraiso Blue Care Spawn 5'),
  ('530', 'SkodaBlue', '[180,[10607.485, 8926.5039,0]]', ' Paraiso Blue Care Spawn 6'),
  ('531', 'SkodaBlue', '[90,[10147.469, 9342.0107,0]]', ' Paraiso Blue Care Spawn 7'),
  ('532', 'SkodaBlue', '[90,[10841.601, 9613.2051,0]]', ' Paraiso Blue Care Spawn 8'),
  ('533', 'SkodaBlue', '[215,[11191.554, 8838.0908,0]]', ' Paraiso Blue Care Spawn 9'),
  ('534', 'SkodaBlue', '[140,[11569.581, 9122.7725,0]]', ' Paraiso Blue Care Spawn 10'),
  ('535', 'PBX', '[140,[3539.8403, 3597.6135,0]]', ' Rahmadi PBX 1'),
  ('536', 'PBX', '[140,[6105.2007, 6918.9087,0]]', ' San Peregrino PBX 1'),
  ('537', 'PBX', '[140,[8721.9717, 4757.6455,0]]', ' Tiberia PBX 1'),
  ('538', 'PBX', '[140,[9669.8643, 3611.7395,0]]', ' San Tomas PBX 1'),
  ('539', 'PBX', '[140,[10283.182, 4585.8486,0]]', ' Iguana PBX 1'),
  ('540', 'PBX', '[140,[11066.049, 6522.374,0]]', ' Dolores PBX 1'),
  ('541', 'PBX', '[140,[13865.942, 7482.4438,0]]', ' Geraldo PBX 1'),
  ('542', 'PBX', '[140,[14868.072, 8206.791,0]]', ' Guala PBX 1'),
  ('543', 'PBX', '[140,[16882.498, 9387.1523,0]]', ' Ancon PBX 1'),
  ('544', 'PBX', '[140,[19361.262, 12905.132,0]]', ' Pita PBX 1'),
  ('545', 'PBX', '[315,[15735.942, 15140.753,0]]', ' Amanitas PBX 1'),
  ('546', 'PBX', '[315,[14295.548, 17088.723,0]]', ' Roca del Dror PBX 1'),
  ('547', 'PBX', '[60,[12265.299, 18345.73,0]]', ' Cabo Santa Lucia PBX 1'),
  ('548', 'PBX', '[60,[10720.145, 16805.041,0]]', ' Cabo Indice PBX 1'),
  ('549', 'PBX', '[60,[6285.0781, 16747.914,0]]', ' Golfo Valiente PBX 1'),
  ('550', 'PBX', '[270,[4981.1714, 16168.875,0]]', ' Isla del Vida PBX 1'),
  ('551', 'PBX', '[270,[4333.666, 15503.652,0]]', ' Isla del Vassal PBX 1'),
  ('552', 'PBX', '[270,[6242.585, 7990.3672,0]]', ' Playa Riscal PBX 1'),
  ('553', 'PBX', '[270,[9446.3564, 11162.274,0]]', ' Rashidah PBX 1'),
  ('554', 'PBX', '[0,[11859.629, 10182.418,0]]', ' Corozal PBX 1'),
  ('555', 'PBX', '[0,[12427.207, 10453.193,0]]', ' Isla Verda PBX 1'),
  ('556', 'PBX', '[0,[12403.51, 10857.137,0]]', ' Isla del Libertad PBX 1'),
  ('557', 'PBX', '[0,[11800.033, 11482.988,0]]', ' Mercalillo PBX 1'),
  ('558', 'PBX', '[0,[6969.5635, 15854.697,0]]', ' Hunapu PBX 1'),
  ('559', 'PBX', '[0,[17900.205, 19009.08,0]]', ' Antigua PBX 1'),
  ('560', 'Fishing_Boat', '[0,[19259.027, 13636.32,0]]', ' Pita Fishing Boat Spawn 1'),
  ('561', 'Fishing_Boat', '[15,[10693.838, 16309.629,0]]', ' Mataredo Fishing Boat Spawn 1'),
  ('562', 'Fishing_Boat', '[15,[7723.25, 15590.342,0]]', ' Hunapo Fishing Boat Spawn 1'),
  ('563', 'Fishing_Boat', '[220,[10973.569, 12501.482,0]]', ' Tlaloc Fishing Boat Spawn 1'),
  ('564', 'Fishing_Boat', '[220,[13162.255, 9079.1172,0]]', ' Corazol Fishing Boat Spawn 1'),
  ('565', 'Fishing_Boat', '[75,[11620.232, 5986.9375,0]]', ' Dolores Fishing Boat Spawn 1'),
  ('566', 'Fishing_Boat', '[75,[11328.428, 5237.4072,0]]', ' Parato Fishing Boat Spawn 1'),
  ('567', 'Fishing_Boat', '[180,[10676.752, 4818.0654,0]]', ' Iguana Fishing Boat Spawn 1'),
  ('568', 'Fishing_Boat', '[180,[7376.2744, 6359.5986,0]]', ' Acadia Fishing Boat Spawn 1'),
  ('569', 'Fishing_Boat', '[180,[6812.1055, 8167.6162,0]]', ' Estrella Fishing Boat Spawn 1'),
  ('570', 'Fishing_Boat', '[180,[7364.0693, 8903.5078,0]]', ' Cedras Fishing Boat Spawn 1'),
  ('571', 'Fishing_Boat', '[180,[8199.1777, 9708.3496,0]]', ' Playa de Palomas Fishing Boat Spawn 1'),
  ('572', 'VolhaLimo_TK_CIV_EP1', '[45,[2837.2305, 2899.4531,0]]', ' Rahmadi Gaz Limo Car Spawn 1'),
  ('573', 'VolhaLimo_TK_CIV_EP1', '[225,[2860.3413, 2902.6147,0]]', ' Rahmadi Gaz Limo Car Spawn 2'),
  ('574', 'VolhaLimo_TK_CIV_EP1', '[345,[2906.2537, 2824.4763,0]]', ' Rahmadi Gaz Limo Car Spawn 3'),
  ('575', 'VolhaLimo_TK_CIV_EP1', '[325,[2886.6301, 2925.7129,0]]', ' Rahmadi Gaz Limo Car Spawn 4'),
  ('576', 'VolhaLimo_TK_CIV_EP1', '[350,[2915.9885, 2871.2891,0]]', ' Rahmadi Gaz Limo Car Spawn 5'),
  ('577', 'Old_moto_TK_Civ_EP1', '[270,[10859.434, 9560.9219,0]]', ' Motorcycle @ Paraiso'),
  ('578', 'Old_moto_TK_Civ_EP1', '[311.18985,[10898.999, 9348.5918,0]]', ' Motorcycle @ Paraiso'),
  ('579', 'Old_moto_TK_Civ_EP1', '[328.63049,[10366.132, 9395.8965,0]]', ' Motorcycle @ Paraiso'),
  ('580', 'Old_moto_TK_Civ_EP1', '[306.12045,[10530.225, 9509.8477,0]]', ' Motorcycle @ Paraiso'),
  ('581', 'Old_moto_TK_Civ_EP1', '[341.14816,[10405.983, 9632.627,0]]', ' Motorcycle @ Paraiso'),
  ('582', 'Old_moto_TK_Civ_EP1', '[375.57761,[10151.496, 9563.6943,0]]', ' Motorcycle @ Paraiso'),
  ('583', 'Old_moto_TK_Civ_EP1', '[372.72055,[10663.656, 9669.2236,0]]', ' Motorcycle @ Paraiso'),
  ('584', 'Old_moto_TK_Civ_EP1', '[180,[10676.335, 9228.1133,0]]', ' Motorcycle @ Paraiso'),
  ('585', 'Old_moto_TK_Civ_EP1', '[90.001312,[10350.357, 9193.7383,0]]', ' Motorcycle @ Paraiso'),
  ('586', 'Old_moto_TK_Civ_EP1', '[270,[10268.525, 9116.4072,0]]', ' Motorcycle @ Paraiso'),
  ('587', 'Old_moto_TK_Civ_EP1', '[360.73993,[10361.708, 9209.5898,0]]', ' Motorcycle @ Paraiso'),
  ('588', 'Old_moto_TK_Civ_EP1', '[270,[9688.6348, 9786.1133,0]]', ' Motorcycle @ Airfield North of Paraiso'),
  ('589', 'Old_moto_TK_Civ_EP1', '[294.90601,[9509.835, 9908.623,0]]', ' Motorcycle @ Airfield North of Paraiso'),
  ('590', 'Old_moto_TK_Civ_EP1', '[357.323,[9456.1211, 9801.5654,0]]', ' Motorcycle @ Airfield North of Paraiso'),
  ('591', 'Old_moto_TK_Civ_EP1', '[358.79608,[8338.5244, 9053.6836,0]]', ' Motorcycle @ Chantico'),
  ('592', 'Old_moto_TK_Civ_EP1', '[500.43362,[8246.6504, 8854.0459,0]]', ' Motorcycle @ Chantico'),
  ('593', 'Old_moto_TK_Civ_EP1', '[213.98854,[7835.1563, 9738.0068,0]]', ' Motorcycle @ Cabo Canino'),
  ('594', 'Old_moto_TK_Civ_EP1', '[142.33943,[7623.1875, 9099.9619,0]]', ' Motorcycle @ Ambergris'),
  ('595', 'Old_moto_TK_Civ_EP1', '[345.52283,[7388.894, 8728.168,0]]', ' Motorcycle @ Cedras'),
  ('596', 'Old_moto_TK_Civ_EP1', '[167.62779,[7353.4702, 8725.3496,0]]', ' Motorcycle @ Cedras'),
  ('597', 'Old_moto_TK_Civ_EP1', '[396.5437,[7244.0698, 8448.6445,0]]', ' Motorcycle @ Calheta de Cedras'),
  ('598', 'Old_moto_TK_Civ_EP1', '[270,[6837.7441, 8062.2646,0]]', ' Motorcycle @ Estrella'),
  ('599', 'Old_moto_TK_Civ_EP1', '[174.28995,[6736.8936, 8046.4541,0]]', ' Motorcycle @ Estrella'),
  ('600', 'Old_moto_TK_Civ_EP1', '[270,[6416.5547, 7464.8765,0]]', ' Motorcycle @ San Peregrino'),
  ('601', 'Old_moto_TK_Civ_EP1', '[367.2374,[6666.6743, 7465.6099,0]]', ' Motorcycle @ San Peregrino'),
  ('602', 'Old_moto_TK_Civ_EP1', '[73.681541,[7632.4214, 6343.7485,0]]', ' Motorcycle @ Arcadia'),
  ('603', 'Old_moto_TK_Civ_EP1', '[245.95219,[7694.6045, 6267.3838,0]]', ' Motorcycle @ Arcadia'),
  ('604', 'Old_moto_TK_Civ_EP1', '[-19.452585,[7731.9312, 6311.5635,0]]', ' Motorcycle @ Arcadia'),
  ('605', 'Old_moto_TK_Civ_EP1', '[-84.072205,[8530.9785, 5461.8433,0]]', ' Motorcycle @ Calha de Cayo'),
  ('606', 'Old_moto_TK_Civ_EP1', '[264.28189,[9356.3584, 5101.48,0]]', ' Motorcycle @ Tiberia'),
  ('607', 'Old_moto_TK_Civ_EP1', '[172.27354,[9390.3799, 5162.2324,0]]', ' Motorcycle @ Tiberia'),
  ('608', 'Old_moto_TK_Civ_EP1', '[-20.763149,[9510.1123, 5367.7451,0]]', ' Motorcycle @ Tiberia'),
  ('609', 'Old_moto_TK_Civ_EP1', '[40.095337,[9171.1514, 5442.9712,0]]', ' Motorcycle @ Tiberia'),
  ('610', 'Old_moto_TK_Civ_EP1', '[136.57152,[9109.3096, 5325.189,0]]', ' Motorcycle @ Tiberia'),
  ('611', 'Old_moto_TK_Civ_EP1', '[30.957001,[10628.369, 4738.5386,0]]', ' Motorcycle @ Iguana'),
  ('612', 'Old_moto_TK_Civ_EP1', '[30.957001,[10629.726, 4737.3896,0]]', ' Motorcycle @ Iguana'),
  ('613', 'Old_moto_TK_Civ_EP1', '[30.957001,[10626.347, 4739.5029,0]]', ' Motorcycle @ Iguana'),
  ('614', 'Old_moto_TK_Civ_EP1', '[-8.0339355,[10766.411, 5057.3076,0]]', ' Motorcycle @ Iguana'),
  ('615', 'Old_moto_TK_Civ_EP1', '[64.514641,[10286.671, 5868.2432,0]]', ' Motorcycle @ Terra Acorcha'),
  ('616', 'Old_moto_TK_Civ_EP1', '[-79.414513,[11457.333, 5542.6748,0]]', ' Motorcycle @ Parato'),
  ('617', 'Old_moto_TK_Civ_EP1', '[-2.4035406,[11204.414, 5285.417,0]]', ' Motorcycle @ Parato'),
  ('618', 'Old_moto_TK_Civ_EP1', '[30.957001,[11340.73, 5864.3623,0]]', ' Motorcycle @ Dolores'),
  ('619', 'Old_moto_TK_Civ_EP1', '[30.957001,[11240.133, 5852.9844,0]]', ' Motorcycle @ Dolores'),
  ('620', 'Old_moto_TK_Civ_EP1', '[56.949314,[11318.239, 6155.9019,0]]', ' Motorcycle @ Dolores'),
  ('621', 'Old_moto_TK_Civ_EP1', '[30.957001,[11494.869, 6386.6738,0]]', ' Motorcycle @ Dolores'),
  ('622', 'Old_moto_TK_Civ_EP1', '[30.957001,[11891.87, 6187.7402,0]]', ' Motorcycle @ Dolores'),
  ('623', 'Old_moto_TK_Civ_EP1', '[222.25598,[8823.9668, 7867.7207,0]]', ' Motorcycle @ Gulan'),
  ('624', 'Old_moto_TK_Civ_EP1', '[54.011993,[7998.2744, 7954.1416,0]]', ' Motorcycle @ Gulan'),
  ('625', 'Old_moto_TK_Civ_EP1', '[80.985542,[9144.2949, 8248.9141,0]]', ' Motorcycle @ Somato'),
  ('626', 'Old_moto_TK_Civ_EP1', '[-86.369537,[9088.9492, 8253.251,0]]', ' Motorcycle @ Somato'),
  ('627', 'Old_moto_TK_Civ_EP1', '[269.36398,[9195.0166, 8302.8291,0]]', ' Motorcycle @ Somato'),
  ('628', 'Old_moto_TK_Civ_EP1', '[30.957001,[8986.1436, 8484.4619,0]]', ' Motorcycle @ Somato'),
  ('629', 'Old_moto_TK_Civ_EP1', '[14.24921,[10223.311, 8387.1689,0]]', ' Motorcycle @ Pesto'),
  ('630', 'Old_moto_TK_Civ_EP1', '[-39.920162,[11152.25, 8894.8613,0]]', ' Motorcycle @ Bonanza'),
  ('631', 'Old_moto_TK_Civ_EP1', '[-198.20724,[11214.704, 8839.4629,0]]', ' Motorcycle @ Bonanza'),
  ('632', 'Old_moto_TK_Civ_EP1', '[3.51561,[11627.329, 9207.2217,0]]', ' Motorcycle @ Corinto'),
  ('633', 'Old_moto_TK_Civ_EP1', '[3.51561,[11615.867, 9161.8926,0]]', ' Motorcycle @ Corinto'),
  ('634', 'Old_moto_TK_Civ_EP1', '[3.51561,[13226.329, 6558.4863,0]]', ' Motorcycle @ Calheta Seca'),
  ('635', 'Old_moto_TK_Civ_EP1', '[3.51561,[13233.313, 6846.2051,0]]', ' Motorcycle @ Geraldo'),
  ('636', 'Old_moto_TK_Civ_EP1', '[3.51561,[13305.65, 6938.2188,0]]', ' Motorcycle @ Geraldo'),
  ('637', 'Old_moto_TK_Civ_EP1', '[3.51561,[12508.215, 7123.8672,0]]', ' Motorcycle @ Ortego'),
  ('638', 'Old_moto_TK_Civ_EP1', '[-183.97455,[12218.471, 7142.4829,0]]', ' Motorcycle @ Ortego'),
  ('639', 'Old_moto_TK_Civ_EP1', '[18.977875,[12272.01, 7016.1484,0]]', ' Motorcycle @ Ortego'),
  ('640', 'Old_moto_TK_Civ_EP1', '[34.484192,[11855.942, 7314.7124,0]]', ' Motorcycle @ Ortego'),
  ('641', 'Old_moto_TK_Civ_EP1', '[3.51561,[1567.3268, 1653.8611,0]]', ' Motorcycle @ Isla de la Caja'),
  ('642', 'Old_moto_TK_Civ_EP1', '[91.215149,[1624.3542, 2343.1494,0]]', ' Motorcycle @ Isla Arimar'),
  ('643', 'Old_moto_TK_Civ_EP1', '[37.202072,[2534.8469, 2999.0881,0]]', ' Motorcycle @ Rahmadi'),
  ('644', 'Old_moto_TK_Civ_EP1', '[-138.0657,[2874.1465, 2905.5957,0]]', ' Motorcycle @ Rahmadi'),
  ('645', 'Old_moto_TK_Civ_EP1', '[3.51561,[2894.4324, 2871.9189,0]]', ' Motorcycle @ Rahmadi'),
  ('646', 'Old_moto_TK_Civ_EP1', '[-101.46629,[2948.9932, 2923.8586,0]]', ' Motorcycle @ Rahmadi'),
  ('647', 'Old_moto_TK_Civ_EP1', '[-31.940228,[3316.6338, 3253.9539,0]]', ' Motorcycle @ Rahmadi'),
  ('648', 'Old_moto_TK_Civ_EP1', '[55.640766,[3324.0486, 2425.9485,0]]', ' Motorcycle @ Rahmadi'),
  ('649', 'Old_moto_TK_Civ_EP1', '[3.51561,[14434.059, 12494.124,0]]', ' Motorcycle @ Bagango'),
  ('650', 'Old_moto_TK_Civ_EP1', '[3.51561,[14601.452, 12587.808,0]]', ' Motorcycle @ Bagango'),
  ('651', 'Old_moto_TK_Civ_EP1', '[3.51561,[14448.432, 10605.908,0]]', ' Motorcycle @ Obregan'),
  ('652', 'Old_moto_TK_Civ_EP1', '[3.51561,[14604.815, 10949.22,0]]', ' Motorcycle @ Obregan'),
  ('653', 'Old_moto_TK_Civ_EP1', '[3.51561,[13780.142, 9298.5332,0]]', ' Motorcycle @ Corazol'),
  ('654', 'Old_moto_TK_Civ_EP1', '[3.51561,[12778.605, 8639.9258,0]]', ' Motorcycle @ Corazol'),
  ('655', 'Old_moto_TK_Civ_EP1', '[3.51561,[13374.251, 8983.8223,0]]', ' Motorcycle @ Corazol'),
  ('656', 'Old_moto_TK_Civ_EP1', '[48.516243,[16591.258, 9193.1299,0]]', ' Motorcycle @ Everon'),
  ('657', 'Old_moto_TK_Civ_EP1', '[93.515602,[17623.658, 10027.447,0]]', ' Motorcycle @ Mato Virgo'),
  ('658', 'Old_moto_TK_Civ_EP1', '[86.893616,[18425.275, 11423.811,0]]', ' Motorcycle @ Sierra de los Pinos'),
  ('659', 'Old_moto_TK_Civ_EP1', '[-96.789703,[17623.66, 14268.254,0]]', ' Motorcycle @ Masbete'),
  ('660', 'Old_moto_TK_Civ_EP1', '[3.51561,[19304.469, 13673.507,0]]', ' Motorcycle @ Pita'),
  ('661', 'Old_moto_TK_Civ_EP1', '[3.51561,[19071.74, 13673.508,0]]', ' Motorcycle @ Pita'),
  ('662', 'Old_moto_TK_Civ_EP1', '[64.208672,[12770.049, 15071.819,0]]', ' Motorcycle @ Eponia'),
  ('663', 'Old_moto_TK_Civ_EP1', '[3.51561,[13072.55, 15018.153,0]]', ' Motorcycle @ Eponia'),
  ('664', 'Old_moto_TK_Civ_EP1', '[-12.639399,[12510.492, 13448.833,0]]', ' Motorcycle @ Carmen'),
  ('665', 'Old_moto_TK_Civ_EP1', '[-49.081985,[11365.881, 12406.437,0]]', ' Motorcycle @ Tlaloc'),
  ('666', 'Old_moto_TK_Civ_EP1', '[-39.353989,[10549.028, 14632.265,0]]', ' Motorcycle @ Pacamac'),
  ('667', 'Old_moto_TK_Civ_EP1', '[-31.915462,[10309.103, 14685.722,0]]', ' Motorcycle @ Pacamac'),
  ('668', 'Old_moto_TK_Civ_EP1', '[3.51561,[8521.4375, 15354.316,0]]', ' Motorcycle @ Hunapu'),
  ('669', 'Old_moto_TK_Civ_EP1', '[3.51561,[6281.7036, 17233.531,0]]', ' Motorcycle @ Cabo Valiente'),
  ('670', 'Old_moto_TK_Civ_EP1', '[3.51561,[12470.533, 18073.279,0]]', ' Motorcycle @ Cabo Santa Lucia'),
  ('671', 'Old_moto_TK_Civ_EP1', '[-24.789429,[10544.369, 17042.229,0]]', ' Motorcycle @ Cabo Indice'),
  ('672', 'Old_moto_TK_Civ_EP1', '[43.804947,[10827.896, 16123.455,0]]', ' Motorcycle @ Mataredo'),
  ('673', 'Old_moto_TK_Civ_EP1', '[3.51561,[10664.498, 15404.491,0]]', ' Motorcycle @ Passo Paradiso'),
  ('674', 'Old_moto_TK_Civ_EP1', '[-53.226376,[11710.507, 13000.396,0]]', ' Motorcycle @ Puntas Oriental'),
  ('675', 'Old_moto_TK_Civ_EP1', '[41.498711,[11956.648, 14473.627,0]]', ' Motorcycle @ Tandag'),
  ('676', 'Old_moto_TK_Civ_EP1', '[-56.193615,[15447.313, 13655.933,0]]', ' Motorcycle @ Benoma'),
  ('677', 'Old_moto_TK_Civ_EP1', '[3.51561,[11202.605, 16966.027,0]]', ' Motorcycle @ Isla de Victoria'),
  ('678', 'Old_moto_TK_Civ_EP1', '[3.51561,[17853.947, 11989.205,0]]', ' Motorcycle @ Tres Valles'),
  ('679', 'Old_moto_TK_Civ_EP1', '[3.51561,[18001.93, 11825.646,0]]', ' Motorcycle @ Tres Valles'),
  ('680', 'Old_moto_TK_Civ_EP1', '[-119.49542,[17215.295, 11249.302,0]]', ' Motorcycle @ Sierra de los Pinos'),
  ('681', 'Old_moto_TK_Civ_EP1', '[3.51561,[13336.643, 11412.859,0]]', ' Motorcycle @ Mercalillo'),
  ('682', 'Old_moto_TK_Civ_EP1', '[-127.23187,[14168.706, 14021.494,0]]', ' Motorcycle @ Terra Marismo'),
  ('683', 'Old_moto_TK_Civ_EP1', '[-158.63794,[15307.798, 12334.668,0]]', ' Motorcycle @ Passo San Marco'),
  ('684', 'Old_moto_TK_Civ_EP1', '[-23.573015,[15424.803, 9818.2832,0]]', ' Motorcycle @ Valor'),
  ('685', 'Old_moto_TK_Civ_EP1', '[3.51561,[15560.249, 8696.4502,0]]', ' Motorcycle @ Bajo Valor'),
  ('686', 'Old_moto_TK_Civ_EP1', '[70.384766,[14497.693, 8424.2236,0]]', ' Motorcycle @ Gaula'),
  ('687', 'Old_moto_TK_Civ_EP1', '[-75.076279,[14515.256, 9636.0654,0]]', ' Motorcycle @ Modesta'),
  ('688', 'Old_moto_TK_Civ_EP1', '[3.51561,[14023.495, 15756.743,0]]', ' Motorcycle @ Passo Epone'),
  ('689', 'Old_moto_TK_Civ_EP1', '[-58.183617,[18416.209, 13155.498,0]]', ' Motorcycle @ Sierra Pita'),
  ('690', 'Old_moto_TK_Civ_EP1', '[3.51561,[4486.3516, 15562.463,0]]', ' Motorcycle @ Isla del Vassal'),
  ('691', 'Old_moto_TK_Civ_EP1', '[3.51561,[5060.5864, 15796.89,0]]', ' Motorcycle @ Isla del Vida'),
  ('692', 'Old_moto_TK_Civ_EP1', '[-96.978615,[5700.458, 16473.895,0]]', ' Motorcycle @ Cabo de Fidel'),
  ('693', 'Old_moto_TK_Civ_EP1', '[93.543686,[7752.6011, 15784.851,0]]', ' Motorcycle @ Hunapu'),
  ('694', 'Old_moto_TK_Civ_EP1', '[65.376343,[10293.475, 15761.352,0]]', ' Motorcycle @ Passo Paradiso'),
  ('695', 'uaz_unarmed_un_ep1', '[-17.73317,[11137.142, 8799.3809,0]]', ' '),
  ('696', 'uh1h_dz', '[0,[11384.136, 8732.0225,0]]', ' '),
  ('697', 'caa1_ah6_chdkz', '[89.312973,[4553.4482, 15288.663,0]]', ' '),
  ('698', 'AH6X_DZ', '[0,[4917.5708, 15464.22,0]]', ' '),
  ('699', 'AH6X_DZ', '[0,[4391.8359, 15807.627,0]]', ' '),
  ('700', 'vwgolf', '[0,[13142.78, 8861.9707,0]]', ' '),
  ('701', 'landrover_tk_civ_ep1', '[-176.43568,[13331.444, 9206.9463,0]]', ' '),
  ('702', 'uh1h_dz', '[0,[13268.191, 9124.9668,0]]', ' '),
  ('703', 'old_bike_tk_civ_ep1', '[0,[13575.375, 9107.1074,0]]', ' '),
  ('704', 'ikarus_tk_civ_ep1', '[-40.42363,[13464.382, 8947.2627,0]]', ' '),
  ('705', 'pbx', '[-106.0659,[13069.369, 9068.0039,0]]', ' '),
  ('706', 'pbx', '[49.042007,[13084.14, 9069.8037,0]]', ' '),
  ('707', 'warfarebbarracks', '[0,[12435.43, 8542.3682,0]]', ' '),
  ('708', 'warfarebwestheavyfactory', '[-77.424004,[12516.449, 8562.2861,0]]', ' '),
  ('709', 'uh60_wreck_ep1', '[0,[12458.551, 8506.7725,0]]', ' '),
  ('710', 'uh60_wreck_ep1', '[0,[12561.452, 8509.3027,0]]', ' '),
  ('711', 'uralwreck', '[0,[12563.634, 8515.9219,0]]', ' '),
  ('712', 'base_warfarebcontructionsite', '[-192.18857,[8262.4326, 9184.002,0]]', ' '),
  ('713', 'base_warfarebcontructionsite', '[-54.839935,[8192.9824, 9172.7441,0]]', ' '),
  ('714', 'us_warfarebbarracks_base_ep1', '[88.902695,[9017.3652, 8208.1797,0]]', ' '),
  ('715', 'land_a_generalstore_01a', '[362.26242,[7735.8276, 6370.5557,0]]', ' '),
  ('716', 'land_a_generalstore_01a', '[-180.54524,[9389.5566, 5970.1074,0]]', ' '),
  ('717', 'land_a_generalstore_01a', '[-199.76781,[10907.879, 5053.5337,0]]', ' '),
  ('718', 'land_a_generalstore_01a', '[-222.60593,[11565.362, 5814.4839,0]]', ' '),
  ('719', 'land_a_generalstore_01a', '[-245.12224,[11473.569, 5863.9575,0]]', ' '),
  ('720', 'land_a_generalstore_01a', '[-1.0425414,[11264.242, 5915.2656,0]]', ' '),
  ('721', 'land_a_generalstore_01a', '[626.56323,[12674.209, 6817.1396,0]]', ' '),
  ('722', 'land_a_generalstore_01a', '[-120.88735,[12139.657, 7269.5229,0]]', ' '),
  ('723', 'land_a_hospital', '[-67.423927,[12729.122, 8084.4761,0]]', ' '),
  ('724', 'land_a_generalstore_01a', '[93.210449,[12998.923, 8514.375,0]]', ' '),
  ('725', 'land_a_generalstore_01a', '[226.64822,[13528.492, 9201.2012,0]]', ' '),
  ('726', 'land_a_hospital', '[-168.57401,[10542.361, 8974.7695,0]]', ' '),
  ('727', 'land_a_generalstore_01a', '[260.53879,[10526.049, 9705.085,0]]', ' '),
  ('728', 'land_a_generalstore_01a', '[159.28708,[10765.301, 9327.9922,0]]', ' '),
  ('729', 'vwgolf', '[72.605347,[11208.586, 8845.0732,0]]', ' '),
  ('730', 'vwgolf', '[0,[11555.468, 9199.0186,0]]', ' '),
  ('731', 'vwgolf', '[-50.632935,[10606.456, 9365.6699,0]]', ' '),
  ('732', 'vwgolf', '[180.29549,[9163.5713, 8260.0605,0]]', ' '),
  ('733', 'vwgolf', '[-176.97333,[8192.458, 8861.873,0]]', ' '),
  ('734', 'vwgolf', '[3.9337673,[8198.4707, 8861.4111,0]]', ' '),
  ('735', 'vwgolf', '[5.7347598,[7628.5347, 9093.1201,0]]', ' '),
  ('736', 'vwgolf', '[-48.020252,[8055.5059, 9356.1152,0]]', ' '),
  ('737', 'vwgolf', '[14.120076,[7666.0435, 6250.6265,0]]', ' '),
  ('738', 'vwgolf', '[1.3864893,[9227.4912, 5840.8984,0]]', ' '),
  ('739', 'vwgolf', '[-180.69913,[9233.6064, 5841.6069,0]]', ' '),
  ('740', 'vwgolf', '[78.963821,[9265.5107, 5166.4258,0]]', ' '),
  ('741', 'vwgolf', '[-255.46085,[10640.636, 4765.0474,0]]', ' '),
  ('742', 'vwgolf', '[28.057159,[10703.331, 5153.8315,0]]', ' '),
  ('743', 'vwgolf', '[-102.84504,[11233.393, 5248.0547,0]]', ' '),
  ('744', 'vwgolf', '[0,[11630.577, 5948.3574,0]]', ' '),
  ('745', 'vwgolf', '[-138.4113,[11577.93, 6138.7817,0]]', ' '),
  ('746', 'vwgolf', '[-29.121077,[12320.95, 7063.3037,0]]', ' '),
  ('747', 'vwgolf', '[44.059124,[14436.021, 8526.9678,0]]', ' '),
  ('748', 'vwgolf', '[0,[16474.428, 9267.4219,0]]', ' '),
  ('749', 'vwgolf', '[-48.810955,[14401.734, 10869.619,0]]', ' '),
  ('750', 'vwgolf', '[-15.684053,[13285.322, 11397.932,0]]', ' '),
  ('751', 'vwgolf', '[0,[14134.22, 12557.956,0]]', ' '),
  ('752', 'vwgolf', '[-36.950245,[17357.977, 14280.118,0]]', ' '),
  ('753', 'vwgolf', '[7.9785676,[12681.122, 15092.89,0]]', ' '),
  ('754', 'vwgolf', '[0,[10611.216, 16147.297,0]]', ' '),
  ('755', 'vwgolf', '[219.63371,[7759.1118, 15772.262,0]]', ' '),
  ('756', 'old_bike_tk_civ_ep1', '[-85.217308,[10370.564, 9429.9453,0]]', ' '),
  ('757', 'old_bike_tk_civ_ep1', '[-90.487289,[10417.252, 9523.3232,0]]', ' '),
  ('758', 'old_bike_tk_civ_ep1', '[91.285843,[10555.114, 9598.6406,0]]', ' '),
  ('759', 'old_bike_tk_civ_ep1', '[148.25641,[10380.695, 9587.1885,0]]', ' '),
  ('760', 'old_bike_tk_civ_ep1', '[81.869507,[10778.428, 9631.6748,0]]', ' '),
  ('761', 'old_bike_tk_civ_ep1', '[79.221519,[10833.484, 9383.2568,0]]', ' '),
  ('762', 'old_bike_tk_civ_ep1', '[-41.197311,[10581.705, 9258.7676,0]]', ' '),
  ('763', 'old_bike_tk_civ_ep1', '[-84.456589,[10976.893, 9420.6982,0]]', ' '),
  ('764', 'old_bike_tk_civ_ep1', '[-39.620136,[10876.649, 9469.8564,0]]', ' '),
  ('765', 'old_bike_tk_civ_ep1', '[-89.592476,[10618.183, 9303.5938,0]]', ' '),
  ('766', 'old_bike_tk_civ_ep1', '[-45.966557,[10750.477, 8778.0928,0]]', ' '),
  ('767', 'old_bike_tk_civ_ep1', '[78.7006,[11178.175, 8882.2988,0]]', ' '),
  ('768', 'old_bike_tk_civ_ep1', '[0,[10854.894, 8606.4531,0]]', ' '),
  ('769', 'old_bike_tk_civ_ep1', '[4.2122107,[11635.818, 9072.2285,0]]', ' '),
  ('770', 'old_bike_tk_civ_ep1', '[-44.829987,[11444.519, 9098.3994,0]]', ' '),
  ('771', 'old_bike_tk_civ_ep1', '[-56.038536,[11946.504, 9342.502,0]]', ' '),
  ('772', 'old_bike_tk_civ_ep1', '[-217.2023,[12378.263, 10360.327,0]]', ' '),
  ('773', 'old_bike_tk_civ_ep1', '[-89.482925,[12493.199, 10838.49,0]]', ' '),
  ('774', 'old_bike_tk_civ_ep1', '[-248.19809,[9355.9717, 10965.943,0]]', ' '),
  ('775', 'old_bike_tk_civ_ep1', '[137.08963,[8322.1543, 9733.1523,0]]', ' '),
  ('776', 'old_bike_tk_civ_ep1', '[83.668098,[8312.4951, 9725.1777,0]]', ' '),
  ('777', 'old_bike_tk_civ_ep1', '[80.451363,[8312.2109, 9726.0664,0]]', ' '),
  ('778', 'atv_cz_ep1', '[110.74698,[8302.1123, 9710.0576,0]]', ' '),
  ('779', 'atv_cz_ep1', '[92.591911,[8294.1797, 9696.7607,0]]', ' '),
  ('780', 'old_bike_tk_ins_ep1', '[91.458679,[8281.9424, 9685.6914,0]]', ' '),
  ('781', 'old_bike_tk_ins_ep1', '[135.7144,[8280.6309, 9678.333,0]]', ' '),
  ('782', 'old_bike_tk_ins_ep1', '[-5.3417916,[8273.5547, 9669.5059,0]]', ' '),
  ('783', 'M1030_US_DES_EP1', '[-223.55928,[8262.2666, 9658.666,0]]', ' '),
  ('784', 'M1030_US_DES_EP1', '[-226.30313,[8262.7764, 9659.3232,0]]', ' '),
  ('785', 'lada1_tk_civ_ep1', '[-197.33434,[8241.2959, 9515.4678,0]]', ' '),
  ('786', 'lada1_tk_civ_ep1', '[55.328445,[8263.4463, 9571.1543,0]]', ' '),
  ('787', 'UralCivil', '[-52.810852,[19288.889, 13872.466,0]]', ' '),
  ('788', 'UralCivil', '[-49.282665,[19185.73, 13959.142,0]]', ' '),
  ('789', 'UralCivil', '[-3.1284053,[9689.7842, 9967.7783,0]]', ' '),
  ('790', 'policecar', '[-65.740524,[10929.167, 5053.0239,0]]', ' '),
  ('791', 'lada1_tk_civ_ep1', '[31.440821,[10754.076, 5042.9971,0]]', ' '),
  ('792', 'old_bike_tk_civ_ep1', '[-18.446497,[10731.33, 4922.2314,0]]', ' '),
  ('793', 'suv_tk_ep1', '[16.090021,[6912.8882, 8043.8315,0]]', ' '),
  ('794', 'hilux1_civil_3_open', '[-18.631977,[7361.979, 7429.1143,0]]', ' ');

-- 
-- Dumping data for table player_data
--
-- Table hivemind.player_data does not contain any data (it is empty)

-- 
-- Dumping data for table player_login
--
-- Table hivemind.player_login does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;